README.md

This pull request updates the `README.md` file to enhance its content and structure, providing more detailed descriptions, visuals, and examples for the `@autobe` project and related tools. The changes aim to improve clarity, highlight features, and showcase integration with complementary projects.
* Updated the project title to "AutoBE, Vibe Coding Agent of Backend Server" and added badges for license, NPM version, downloads, build status, and Discord. These updates improve branding and provide quick access to project metrics.
* Expanded the project description to emphasize the integration of `@autobe` with `@agentica` and `@autoview`, highlighting the potential for full-stack automation.
* Added a "Blueprint" section with a flowchart illustrating the "Full Stack Vibe Coding" concept, …

Complement README content

---

.github/workflows/build.yml
assets/compiler-dependencies/package-lock.json
assets/compiler-dependencies/package.json
package.json
packages/compiler/build/typings.ts
packages/interface/package.json
pnpm-workspace.yaml

This pull request includes updates to dependencies, restructuring of the project directory, and enhancements to the build and packaging scripts. Key changes include upgrading several dependencies, moving `compiler-dependencies` to the `assets` directory, and adding new scripts for building and publishing packages.
* Upgraded `@samchon/openapi` from `4.2.0` to `4.3.0` in `package.json`, `package-lock.json`, and `pnpm-workspace.yaml` files. [[1]](diffhunk://#diff-37c9ac20d91a5ec2b659e96bfac64271f9e85a1233afefecbbb1784e5b6be14aL24-R24) [[2]](diffhunk://#diff-37c9ac20d91a5ec2b659e96bfac64271f9e85a1233afefecbbb1784e5b6be14aL1298-R1300) [[3]](diffhunk://#diff-f498d63806f25ff19cdeb7f99f1b19c7ebbbabd9390422c940d04f37b9399063L20-R20)  
* Upgraded `typia` from `9.1.1` to `9.3.0` in `package.json` …

Prepare publishing configuration

---

packages/agent/prompts/PRISMA_COMPILER.md
packages/agent/prompts/PRISMA_COMPONENT.md
packages/agent/prompts/PRISMA_SCHEMA.md
packages/agent/src/orchestrate/prisma/orchestratePrisma.ts
packages/agent/src/orchestrate/prisma/orchestratePrismaCompiler.ts
packages/agent/src/orchestrate/prisma/orchestratePrismaComponent.ts
packages/agent/src/orchestrate/prisma/orchestratePrismaSchema.ts
packages/agent/src/orchestrate/prisma/transformPrismaCompilerHistories.ts
packages/agent/src/orchestrate/prisma/transformPrismaComponentsHistories.ts
packages/agent/src/orchestrate/prisma/transformPrismaSchemaHistories.ts
packages/interface/src/events/AutoBeEvent.ts
packages/interface/src/events/AutoBePrismaComponentsEvent.ts
packages/interface/src/events/AutoBePrismaSchemasEvent.ts
packages/interface/src/json/IAutoBeEventJson.ts
test/src/features/prisma/internal/validate_agent_prisma.ts

- Fix prisma schema Agent structure.
- Fix the Prisma Agent Prompt.

fix(agent): Prisma Agent Prompt

---

packages/agent/src/orchestrate/orchestrateAnalyze.ts

This pull request updates the `orchestrateAnalyze` function in `packages/agent/src/orchestrate/orchestrateAnalyze.ts` to improve the handling of state transitions and replace the UUID generation library. The most important changes include switching from the `crypto` library to `uuid` for generating UUIDs, adding state dispatch actions for better tracking of the analysis process, and restructuring the return objects for consistency.
* Replaced the `randomUUID` function from the `crypto` library with the `v4` function from the `uuid` library for generating unique identifiers. (`[packages/agent/src/orchestrate/orchestrateAnalyze.tsL6-R7](diffhunk://#diff-0760076d2713c7b74179a23fe6dfd2a97aa15f908f6752174db0d94d521dc9bcL6-R7)`)
* Added a `step` variable to track the current step of the …

feat(agent): dispatch analyze events

---

test/assets/repositories/kakasoo/sns/docs/requirements/01_user_requirement_report_toc.md
test/assets/repositories/kakasoo/sns/docs/requirements/02_service_overview.md
test/assets/repositories/kakasoo/sns/docs/requirements/03_user_personas.md
test/assets/repositories/kakasoo/sns/docs/requirements/04_service_values.md
test/assets/repositories/kakasoo/sns/docs/requirements/05_functional_requirements.md
test/assets/repositories/kakasoo/sns/docs/requirements/06_nonfunctional_requirements.md
test/assets/repositories/kakasoo/sns/docs/requirements/07_user_journeys.md
test/assets/repositories/kakasoo/sns/docs/requirements/08_acceptance_criteria.md
test/assets/repositories/kakasoo/sns/docs/requirements/09_data_model_erd.md
test/assets/repositories/kakasoo/sns/docs/requirements/10_search_recommendations.md
test/assets/repositories/kakasoo/sns/docs/requirements/11_future_scope.md
test/assets/repositories/kakasoo/sns/prisma/schema/main.prisma
test/src/features/prisma/internal/prepare_agent_prisma.ts
test/src/features/prisma/test_agent_prisma_sns.ts
typos.toml

I've tried adding some very complex requirements. No matter how long I wait in my local area, I don't get results.

add test case for sns in prisma agent

---

packages/agent/src/orchestrate/prisma/orchestratePrismaCompiler.ts
packages/interface/src/events/AutoBeEvent.ts
packages/interface/src/events/AutoBePrismaCorrectEvent.ts
packages/interface/src/events/index.ts
packages/interface/src/json/IAutoBeEventJson.ts
packages/interface/src/rpc/IAutoBeRpcListener.ts
packages/playground-ui/src/movies/events/AutoBePlaygrounPrismaCorrectEventMovie.tsx
packages/playground-ui/src/movies/events/AutoBePlaygroundEventMovie.tsx
packages/playground-ui/src/movies/events/AutoBePlaygroundPrismaCorrectEventMovie.tsx
packages/playground-ui/src/movies/events/AutoBePlaygroundPrismaValidateEventMovie.tsx
packages/playground-ui/src/structures/AutoBePlaygroundListener.ts
test/src/features/prisma/internal/validate_agent_prisma.ts

This pull request introduces a new event type, `prismaCorrect`, to handle scenarios where Prisma schema compilation errors occur and corrections are attempted. The changes span multiple files, adding support for this event across the orchestration, event interfaces, and UI components. Below is a summary of the most important changes:
* **Orchestration Logic**:
- Added dispatch logic for `prismaCorrect` events in the Prisma compiler orchestration (`async function step` in `orchestratePrismaCompiler.ts`). This includes reporting the input files, failure details, corrections, and reasoning.
* **Event Interfaces**:
- Introduced `AutoBePrismaCorrectEvent` interface to define the structure of the `prismaCorrect` event, including properties like `input`, `failure`, `correction`, `reason`, and …

feat(interface): new event type `prismaCorrect` for testing.

---

packages/agent/prompts/PRISMA_COMPILER.md
packages/agent/prompts/PRISMA_SCHEMA.md

This pull request introduces comprehensive updates to the Prisma schema validation and error resolution guidelines, focusing on preventing and resolving duplication issues. Key changes include new rules, checklists, and processes to ensure schema integrity, as well as updates to error resolution workflows and quality assurance steps.
* Added rules to prevent duplicate columns, relations, and model names within and across schema files, emphasizing the importance of uniqueness for schema integrity. (`packages/agent/prompts/PRISMA_COMPILER.md`, [[1]](diffhunk://#diff-c7e21e290ef0a1f48895181cb843d43590db818d8ba1b0d1a858934d9ff3d6c8R15-R17) [[2]](diffhunk://#diff-c7e21e290ef0a1f48895181cb843d43590db818d8ba1b0d1a858934d9ff3d6c8R28-R46)
* Introduced a "Mandatory Duplication Prevention & Review …

feat(agent): enhance prompt of prisma about duplicate statements

---

packages/agent/prompts/INTERFACE_COMPLEMENT.md
packages/agent/src/orchestrate/interface/orchestrateInterface.ts
packages/agent/src/orchestrate/interface/orchestrateInterfaceComplement.ts
packages/agent/src/orchestrate/interface/orchestrateInterfaceComponents.ts
packages/agent/src/orchestrate/interface/orchestrateInterfaceEndpoints.ts
packages/agent/src/orchestrate/interface/orchestrateInterfaceOperations.ts
packages/agent/src/orchestrate/interface/transformInterfaceHistories.ts
packages/agent/src/orchestrate/prisma/orchestratePrismaCompiler.ts
packages/interface/src/events/AutoBeEvent.ts
packages/interface/src/events/AutoBeInterfaceComplementEvent.ts
packages/interface/src/events/index.ts
packages/interface/src/json/IAutoBeEventJson.ts
packages/playground-server/src/AutoBePlaygroundServer.ts
packages/playground-ui/src/movies/events/AutoBePlaygroundEventMovie.tsx
packages/playground-ui/src/movies/events/AutoBePlaygroundProgressEventMovie.tsx
test/package.json
test/src/features/prisma/internal/validate_agent_prisma.ts

This pull request introduces a new feature for automatically complementing missing schema definitions in OpenAPI documents and includes several related updates across the codebase. The changes primarily focus on adding functionality to detect and fill missing schema references, integrating this feature into the existing orchestration pipeline, and improving code consistency.
* **`packages/agent/prompts/INTERFACE_COMPLEMENT.md`**: Added detailed documentation for the new "OpenAPI Schema Complement Agent," outlining its role, responsibilities, and guidelines for generating missing schema definitions.
* **`packages/agent/src/orchestrate/interface/orchestrateInterfaceComplement.ts`**: Introduced the `orchestrateInterfaceComplement` function to identify and recursively fill missing schema …

feat(agent): new workflow `interfaceComplement`

---

packages/interface/src/rpc/IAutoBeRpcListener.ts
packages/playground-ui/src/structures/AutoBePlaygroundListener.ts
packages/rpc/src/AutoBeRpcService.ts

- Add `testValidate` event to Playground for displaying to the browser.
- add test validation logic to `IAutoBeRpcListener` related files.

fix: Add Test Validate Event to Playground

---

packages/compiler/src/prisma/validatePrismaApplication.ts
test/src/features/compiler/examples/prisma.gin.json
test/src/features/compiler/test_compiler_prisma_gin.ts

This pull request introduces a minor enhancement to the `validateIndexes` function and adds a new test case for validating Prisma applications. The most important changes are grouped into functional improvements and testing additions.
* [`packages/compiler/src/prisma/validatePrismaApplication.ts`](diffhunk://#diff-164d3eb682669163f20ed67300af5dba09a0a7e10ed96c3eff616609fc0268fcR382): Enhanced the `validateIndexes` function by adding an optional callback (`props.additional`) to allow custom logic during index validation.
* [`test/src/features/compiler/test_compiler_prisma_gin.ts`](diffhunk://#diff-3361a048421aac37a0075091c295ace94927f7869a46983c502926dab6656f1fR1-R15): Added a new test case (`test_compiler_prisma_gin`) to validate Prisma applications using the `AutoBePrismaCompiler`. This …

feat(compiler): gin index validation.

---

packages/playground-ui/src/movies/events/AutoBePlaygroundProgressEventMovie.tsx

- Fix the Playground ui output of `Test Scenario` as follow

fix(playgrond-ui): Test Scenario Agent output statement

---

packages/agent/prompts/TEST_CORRECT.md

- Fix the Test Correct System prmopt

chore: fix the test correct prompt

---

packages/agent/src/AutoBeAgent.ts
website/components/LocalSource.tsx
website/components/LocalSourceGroup.tsx
website/components/internal/getLocalSourceFile.ts
website/content/docs/agent/event.mdx
website/content/docs/agent/facade.mdx
website/content/docs/agent/history.mdx
website/content/docs/concepts/compiler.mdx
website/content/docs/concepts/function-calling.mdx
website/content/docs/stack/typescript.mdx
website/content/docs/websocket/client.mdx
website/content/docs/websocket/nestjs.mdx
website/content/docs/websocket/nodejs.mdx

This pull request introduces several changes across the `AutoBeAgent` class and the website documentation components. The key updates include internal refactoring of the `AutoBeAgent` class to improve encapsulation and transitioning documentation components from remote data fetching (`RemoteSource` and `RemoteSourceGroup`) to local file handling (`LocalSource` and `LocalSourceGroup`). These changes enhance code maintainability and improve performance for the documentation pages.
* Added private internal properties (`props_`, `agentica_`, `histories_`, `context_`, `state_`, and `listeners_`) to encapsulate state and ensure immutability.
* Modified the constructor to store `props` in the new private `props_` property, improving encapsulation.
* Updated the `clone` method to use the private …

feat(website): `LocalSourceFile`

---

packages/agent/src/AutoBeAgent.ts

This pull request refactors the `AutoBeAgent` class in `packages/agent/src/AutoBeAgent.ts` to improve code organization and enhance the initialization process for the `vendor` property. The changes include introducing a new `IAgenticaVendor` type, restructuring the `vendor` initialization, and moving the `listeners_` member initialization for better clarity.
* **Introduced `IAgenticaVendor` type**: Added the `IAgenticaVendor` type from `@agentica/core` to improve type safety and clarity when constructing the `vendor` object. (`[packages/agent/src/AutoBeAgent.tsL1-R1](diffhunk://#diff-eb5845bde058399222e7eb37fcc40ccd00bee27a5d2531830decea25dc197e73L1-R1)`)
* **Refactored `vendor` initialization**: Moved the construction of the `vendor` object to the constructor, ensuring it is initialized …

fix(agent): semaphore sharing

---

packages/agent/prompts/TEST_WRITE.md
packages/agent/src/orchestrate/test/compileTestScenario.ts
packages/agent/src/orchestrate/test/orchestrateTest.ts
packages/agent/src/orchestrate/test/orchestrateTestCorrect.ts
packages/agent/src/orchestrate/test/orchestrateTestWrite.ts
packages/agent/src/orchestrate/test/structures/IAutoBeTestScenarioArtifacts.ts
packages/agent/src/orchestrate/test/transformTestCorrectHistories.ts
packages/agent/src/orchestrate/test/transformTestWriteHistories.ts
test/src/features/test/internal/validate_agent_test_write.ts

This pull request introduces significant updates to the `packages/agent` module to standardize import guidelines, improve test orchestration, and refactor code for better maintainability. Key changes include the addition of standardized import rules for E2E test functions, the creation of a `compileTestScenario` utility for handling test artifacts, and the renaming and refactoring of test orchestration processes to align with new conventions.
* Added detailed import guidelines in `TEST_WRITE.md` for E2E test functions, specifying import order (typia, API SDK, DTO types, TestValidator), alphabetical sorting within groups, and explicit imports for better type safety.
* Updated various import statements in example test functions to follow the new guidelines. …

feat(agent): enhance test code writer prompt.

---

test/src/index.ts

add token usage format and number index

fix: test token usesage format

---

README.md
packages/compiler/src/AutoBeCompiler.ts
packages/compiler/src/AutoBeTestCompiler.ts
packages/compiler/src/test/IAutoBeTestProgrammerContext.ts
packages/compiler/src/test/programmers/AutoBeTestAccessorProgrammer.ts
packages/compiler/src/test/programmers/AutoBeTestFunctionalProgrammer.ts
packages/compiler/src/test/programmers/AutoBeTestLiteralProgrammer.ts
packages/compiler/src/test/programmers/AutoBeTestRandomProgrammer.ts
packages/compiler/src/test/programmers/AutoBeTestStatementProgrammer.ts
packages/compiler/src/test/writeTestExpression.ts
packages/compiler/src/test/writeTestFunction.ts
packages/compiler/src/test/writeTestStatement.ts
packages/compiler/src/utils/FilePrinter.ts
packages/interface/src/compiler/IAutoBeCompiler.ts
packages/interface/src/compiler/IAutoBeTestCompiler.ts
packages/interface/src/compiler/IAutoBeTestCompilerProps.ts
packages/interface/src/compiler/index.ts
packages/interface/src/index.ts
packages/interface/src/test/AutoBeTest.ts
packages/interface/src/test/index.ts
website/src/template/AutoBeRoadmapPreface.mdx

TypeScript code generator from `AutoBeTest`, the AST structured data.
----------------------
This pull request introduces a new `AutoBeTestCompiler` to support automated test generation in the `AutoBe` framework. It includes changes to integrate the test compiler into the existing architecture and adds several new modules and utilities for handling test-related programming constructs.
* Added `IAutoBeTestCompiler` to the imports and initialized it as a property in the `AutoBeCompiler` class (`AutoBeCompiler.ts`). [[1]](diffhunk://#diff-f6a904872bb8ad007a0cc7a2277b6f0a5511ed75f1b927616135b87df8b9892dR5-R11) [[2]](diffhunk://#diff-f6a904872bb8ad007a0cc7a2277b6f0a5511ed75f1b927616135b87df8b9892dR44-R45)
* Implemented the `AutoBeTestCompiler` class, which uses the `writeTestFunction` utility …

feat(compiler): `AutoBeTestCompiler.compile()`.

---

packages/compiler/src/test/programmers/AutoBeTestFunctionalProgrammer.ts
packages/compiler/src/test/programmers/AutoBeTestRandomProgrammer.ts
packages/interface/src/histories/contents/AutoBeTestFile.ts
packages/interface/src/test/AutoBeTest.ts
test/src/features/compiler/test_compiler_test_write_random.ts

This pull request introduces significant updates to the `AutoBeTest` framework, focusing on replacing the deprecated `IArrayRandom` expression with new functional array expressions (`IArrayFilterExpression`, `IArrayForEachExpression`, `IArrayMapExpression`, and `IArrayRepeatExpression`). Additionally, it includes updates to the test interface, programmer implementations, and associated test cases to reflect these changes.
* Introduced new functional array expressions (`IArrayFilterExpression`, `IArrayForEachExpression`, `IArrayMapExpression`, `IArrayRepeatExpression`) to support advanced operations like filtering, mapping, iterating, and generating arrays dynamically. These are defined in `packages/interface/src/test/AutoBeTest.ts` with detailed documentation for E2E testing scenarios. …

feat(compiler): array expressions

---

packages/agent/src/orchestrate/realize/orchestrateRealize.ts
packages/agent/src/orchestrate/realize/orchestrateRealizePlanner.ts

I'm making realize coder part. But, For this, I have to make orchestrateRealize first. So, I defined pipe function and FAILED type for stopping pipe and error handling. Anyway, this is just draft PR, but you might wanna merge this PR for creating other  inner agents.

Feat(agent) orchestrate realize pipe handling

---

packages/agent/src/orchestrate/realize/orchestrateRealize.ts
packages/agent/src/orchestrate/realize/orchestrateRealizeIntegrator.ts
packages/agent/src/orchestrate/realize/orchestrateRealizeValidator.ts
test/src/features/realize/internal/validate_agent_realize_integrator.ts

- This branch will be merged into the `feat/agent_realize_integrator` branch.
- Structuring the RealizeValidator Agent.
- Restructured the `orchestrateRealize` function.
- This work is not done yet. so don't merge.

feat(agent): Realize Validator

---

packages/agent/src/utils/forceRetry.ts

This pull request introduces a utility function to improve error handling and retry logic in the `packages/agent/src/utils/forceRetry.ts` file.
* Added a `forceRetry` function that retries a given asynchronous task a specified number of times (default is 2) before throwing the last encountered error. This provides a standardized way to handle transient failures in asynchronous operations.

feat(agent): new function `forceRetry` for accidents.

---

packages/agent/prompts/REALIZE_CODER.md
packages/agent/src/orchestrate/realize/orchestrateRealizeCoder.ts
packages/interface/src/openapi/AutoBeOpenApi.ts
test/src/features/realize/internal/validate_agent_realize_coder.ts

Made the authorization field optional, applied Prettier formatting, and added a default value to the import statement.

Fix authorization to be optional and add test for realize compile

---

internals/template/package.json
packages/agent/src/orchestrate/interface/orchestrateInterfaceComplement.ts
packages/agent/src/orchestrate/interface/orchestrateInterfaceComponents.ts
packages/agent/src/orchestrate/interface/orchestrateInterfaceOperations.ts

This pull request includes updates to dependencies in the `package.json` file and introduces a new utility function, `forceRetry`, to improve error handling across multiple orchestration modules. Below is a summary of the most important changes:
* Updated several `@nestia` packages (`@nestia/benchmark`, `@nestia/e2e`, `@nestia/sdk`, `@nestia/core`, `@nestia/fetcher`) to version `^7.1.0` in `internals/template/package.json`. [[1]](diffhunk://#diff-9e76920512bbc4261065b042e51d3073235e8f98388b13dec2fd0cbaf97aee57L49-R51) [[2]](diffhunk://#diff-9e76920512bbc4261065b042e51d3073235e8f98388b13dec2fd0cbaf97aee57L70-R70) [[3]](diffhunk://#diff-9e76920512bbc4261065b042e51d3073235e8f98388b13dec2fd0cbaf97aee57L87-R88)
* Upgraded `typia` dependency from `^9.3.1` to `^9.5.0` in …

feat(agent): implement forceRetry utility in orchestrate functions for improved error handling

---

internals/template/realize/.gitignore
packages/agent/src/orchestrate/prisma/orchestratePrisma.ts
packages/agent/src/orchestrate/prisma/orchestratePrismaSchema.ts
packages/agent/src/orchestrate/prisma/transformPrismaSchemaHistories.ts
packages/compiler/src/prisma/writePrismaApplication.ts
test/src/features/compiler/examples/prisma.one-to-one.json
test/src/features/compiler/test_compiler_prisma_one_to_one.ts

This pull request introduces several updates to improve Prisma-related functionality, enhance error handling, and add a new test case. The changes include updates to `.gitignore`, enhancements in schema processing, refinements in foreign key handling, and the addition of a one-to-one relationship test for the Prisma compiler.
* [`internals/template/realize/.gitignore`](diffhunk://#diff-7da37d47c588f9b7fd65335430e67b692caac4f30e3a875ef6d1fe162c54a91dR1-R13): Added entries to ignore build artifacts (`bin/`, `dist/`, `lib/`), node modules, Prisma migrations, database files, and lock files. This ensures cleaner version control by excluding unnecessary files.
* [`packages/agent/src/orchestrate/prisma/orchestratePrisma.ts`](diffhunk://#diff-8c1ac6319dd164a39cb8822188e6271b20a9f6fd0136751c6d5c448 …

fix(compiler): prisma unique index to one-to-one relationship.

---

packages/agent/src/orchestrate/test/orchestrateTestCorrect.ts
packages/agent/src/orchestrate/test/orchestrateTestWrite.ts

This pull request refactors the `orchestrateTestCorrect` and `orchestrateTestWrite` functions in the `packages/agent/src/orchestrate/test/` directory to improve error handling and ensure null values are filtered out from the results. The changes enhance code robustness by handling exceptions explicitly and returning only valid results.
Refactoring for improved error handling and result filtering:
* [`packages/agent/src/orchestrate/test/orchestrateTestCorrect.ts`](diffhunk://#diff-884758dfb882ce4573dac533bfef2f812d974b58bd7bd9a384ddb3cb7f47ffd9L26-R30): Updated the `orchestrateTestCorrect` function to wrap the `forceRetry` calls in a `try-catch` block, returning `null` for failed attempts. Added a final step to filter out `null` values from the results before returning them. …

feat(agent): exceptional case for test agents

---

packages/agent/prompts/REALIZE_DECORATOR.md
packages/agent/prompts/REALIZE_DECORATOR_CORRECT.md
packages/agent/src/orchestrate/realize/orchestrateRealizeDecorator.ts
packages/agent/src/orchestrate/realize/structures/IAutoBeRealizeDecoratorApplication.ts
packages/agent/src/orchestrate/realize/transformRealizeDecorator.ts
packages/agent/src/orchestrate/realize/transformRealizeDecoratorCorrectHistories.ts
test/src/features/realize/internal/validate_agent_realize_decorator.ts
test/src/features/realize/test_agent_realize_decorator_shopping.ts

- Fix the Output format of Realize Decorator Agent.
- Add Decorator type for dividing the type file from provider.
- Fix the Realize Decorator Prompt and Realize Decorator Correct Prompt.

Fix(agent): Realize Decorator Prompt

---

README.md
website/articles/autobe-ai-friendly-compilers.md
website/src/template/AutoBePlaygroundSection.mdx

This pull request includes updates to external links and embedded video references in the documentation and website files to ensure they point to the correct resources.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L48-R48): Updated the playground asset link to a new URL for better accessibility.
* [`website/articles/autobe-ai-friendly-compilers.md`](diffhunk://#diff-104e5e4dca18edb69c79a9a38cda90976ebf6e2a06b6dd3950a38ff80c281026L2-R2): Changed the embedded YouTube video reference to a new video ID.
* [`website/src/template/AutoBePlaygroundSection.mdx`](diffhunk://#diff-f71dc825064691ee145ab5fa572685f1ac0674de00fa3d8faef39dfb1c93dbf3L3-R3): Updated the embedded YouTube video source URL to reflect the new video ID.

feat(website): embed subtitles and voices on video

---

packages/interface/src/events/AutoBeRealizeAuthorizationCorrectEvent.ts
packages/interface/src/events/AutoBeRealizeAuthorizationValidateEvent.ts
website/articles/autobe-ai-friendly-compilers.md
website/public/articles/autobe-ai-friendly-compilers.html

This pull request includes updates to improve the clarity and scope of documentation and interfaces related to `AutoBE`, as well as enhancements to the website content to highlight comparisons with AWS Kiro and future development plans. The most important changes are grouped into interface updates and website content enhancements.
* `AutoBeRealizeAuthorizationCorrectEvent` (`packages/interface/src/events/AutoBeRealizeAuthorizationCorrectEvent.ts`): Updated descriptions to broaden the scope from "decorator implementation code" to "authorization implementation code," including providers, payloads, and decorators. This change ensures more comprehensive terminology and alignment with the broader authorization context.
* `AutoBeRealizeAuthorizationValidateEvent` …

feat(website): update article a little bit

---

packages/filesystem/package.json

This pull request updates the metadata of the `@autobe/filesystem` package to better reflect its purpose and improve discoverability. The most important changes include updating the package description, adding repository and issue tracking information, and introducing a comprehensive list of keywords.
* Updated the `description` field in `package.json` to describe the package as an "AI backend server code generator" instead of its previous internal-use description.
* Added `repository` and `bugs` fields to provide links to the package's GitHub repository and issue tracker.
* Added a detailed `keywords` array to `package.json`, including terms such as "ai," "api-design," "nestjs," "prisma," and "typescript," to improve the package's visibility in searches.

fix(filesystem): package.json's repository URL for publishing

---

packages/playground-ui/src/movies/events/AutoBePlaygroundCompleteEventMovie.tsx

This pull request refactors the `AutoBePlaygroundCompleteEventMovie` component in `packages/playground-ui/src/movies/events/AutoBePlaygroundCompleteEventMovie.tsx` to improve state management and user experience. The changes include replacing `useEffect` with `Singleton` for managing asynchronous operations, adding a visual indicator for download progress, and enhancing error handling in asynchronous actions.
* Replaced `useEffect` with `Singleton` to manage asynchronous fetching of `postgres` and `sqlite` files, simplifying the state logic and ensuring that file fetching is encapsulated. (`[[1]](diffhunk://#diff-9bbbeae270749c1754af8527bc90b08b949a4f8d78caeb9eaebae5db77892f5bR12-R58)`, `[[2]](diffhunk://#diff-9bbbeae270749c1754af8527bc90b08b949a4f8d78caeb9eaebae5db77892f5bL65-R80)`)
* …

feat(playground-ui): adjust download status

---

internals/template/realize/src/providers/jwtAuthorize.ts

This pull request includes a small change to the `jwtAuthorize.ts` file. The change updates the import path of the `MyGlobal` module to correct a relative path issue.

fix(compiler): wrong import path from template

---

packages/playground-ui/src/movies/chat/AutoBePlaygroundChatMovie.tsx
packages/playground-ui/src/movies/events/AutoBePlaygroundCompleteEventMovie.tsx
test/scripts/scenario.md

This pull request introduces enhancements to user interaction and functionality in the `AutoBePlaygroundChatMovie` and `AutoBePlaygroundCompleteEventMovie` components, as well as updates to a test scenario document. Key changes include improved input validation, expanded download options, and additional test steps.
* [`packages/playground-ui/src/movies/chat/AutoBePlaygroundChatMovie.tsx`](diffhunk://#diff-b27f9cd729f8d1a53a8258034ec7af32ca93380217ec7e434659b0ed8bf4077dR45): Added validation to prevent sending empty messages. The placeholder and error state of the input field now dynamically reflect this validation. [[1]](diffhunk://#diff-b27f9cd729f8d1a53a8258034ec7af32ca93380217ec7e434659b0ed8bf4077dR45) [[2]](diffhunk://#diff-b27f9cd729f8d1a53a8258034ec7af32ca93380217ec7e434659b0ed8bf407 …

feat(ui): block empty conversation

---

README.md
packages/interface/src/events/AutoBeInterfaceGroupsEvent.ts
packages/interface/src/histories/contents/AutoBeInterfaceGroup.ts
test/src/features/interface/internal/validate_agent_interface_main.ts
test/src/features/realize/internal/validate_agent_realize_main.ts
test/src/features/test/internal/validate_agent_test_main.ts

This pull request introduces detailed documentation and enhancements to the `AutoBeInterfaceGroupsEvent` and `AutoBeInterfaceGroup` interfaces to improve clarity and scalability for API endpoint generation in large-scale projects. The changes focus on defining logical grouping principles, ensuring alignment with Prisma schema structures, and supporting modular development.
* Added comprehensive documentation for the `AutoBeInterfaceGroupsEvent` interface, explaining its purpose in organizing API endpoint groups based on Prisma schema structures for scalability and consistency in large projects.
* Introduced detailed descriptions for the `groups` and `step` properties, clarifying their roles in API organization and tracking schema evolution.
* Added a new interface `AutoBeInterfaceGroup` …

feat(interface): documentation on types

---

packages/agent/src/orchestrate/realize/transformRealizeAuthorizationCorrectHistories.ts

- Fix the System Prompt of `Realize Authorization Correct Agent`.
- define the system prompt about roles.

chore: fix the realize authorization correct system prommpt about role

---

internals/template/test/tsconfig.json

This pull request introduces a new `tsconfig.json` file for the `internals/template/test` directory, which sets up TypeScript compiler options to enhance development and build processes. The configuration includes settings for strict type checking, module resolution, and custom transformations.
* Enabled strict type-checking options, including `strict`, `noUnusedLocals`, `noUnusedParameters`, `noImplicitReturns`, and `noFallthroughCasesInSwitch`, to enforce better code quality.
* Configured the `target` to `ES2015` and `module` to `commonjs` for compatibility with modern JavaScript and Node.js environments.
* Added custom `paths` mapping for simplified module imports, specifically for `@ORGANIZATION/PROJECT-api`.
* Enabled `sourceMap` generation and specified `outDir` as `./lib` for …

feat(agent): add test/realize template for compilation

---

packages/agent/src/orchestrate/prisma/transformPrismaComponentsHistories.ts

- Fix the `transformPrismaComponentsHistories`

Fix(agent): Remove the user request section in prisma component prompt

---

packages/compiler/src/prisma/writePrismaApplication.ts

- add the `pg_trgm` to the postgresql main file in `writePrismaApplication`

fix(agent): Fix the PostgreSQL main file of write prisma application

---

packages/agent/src/orchestrate/prisma/orchestratePrismaComponent.ts

- Fix the tool description of prisma component agent

Fix(agent): Fix the tool description of orchestratePrismaComponent

---

packages/agent/prompts/TEST_SCENARIO.md
packages/agent/prompts/TEST_WRITE.md
packages/agent/src/orchestrate/test/orchestrateTestWrite.ts
packages/agent/src/orchestrate/test/structures/IAutoBeTestScenarioApplication.ts
packages/agent/src/orchestrate/test/transformTestWriteHistories.ts

- The generated e2e test file name and function name is different each other. so, need to match them.
- Fix the comment about functionName property of `IAutoBeTestScenarioApplication.IScenario`.
- Fix the Test Write Prompt to use the `{{FUNCTION_NAME}}` as variable.
- Fix the Test Scenario Prompt about function name.

fix(agent): Fix the Test Agent Prompt about functionName

---

packages/playground-ui/src/contexts/AutoBePlaygroundDragContext.tsx
packages/playground-ui/src/movies/chat/AutoBePlaygroundChatBodyMovie.tsx
packages/playground-ui/src/movies/chat/AutoBePlaygroundChatMovie.tsx
packages/playground-ui/src/movies/chat/AutoBePlaygroundChatPromptMovie.tsx
packages/playground-ui/src/movies/chat/AutoBePlaygroundChatUploadMovie.tsx
packages/playground-ui/src/movies/chat/AutoBePlaygroundChatVoiceMovie.tsx
packages/playground-ui/src/structures/IAutoBePlaygroundBucket.ts
packages/playground-ui/src/structures/IAutoBePlaygroundFileContent.ts
packages/playground-ui/src/structures/IAutoBePlaygroundUploadConfig.ts
packages/playground-ui/src/utils/AutoBePlaygroundFileUploader.ts
packages/playground-ui/src/utils/AutoBePlaygroundVoiceRecorder.ts

This pull request refactors and modularizes the handling of file uploads and audio recording in the `AutoBePlaygroundChatBodyMovie` component. The changes introduce utility classes for file uploading and voice recording, centralizing and simplifying the logic for processing files and audio content. This improves maintainability and code reuse, and removes redundant code from the main component.
**File and audio handling modularization:**
* Added a new utility module `AutoBePlaygroundFileUploader` to encapsulate logic for handling file uploads and content composition, supporting images, audio, and generic files. The main component now delegates file processing to this utility. [[1]](diffhunk://#diff-c46f6b4f855cf8bf230b09513fd82dbac0870ae8403acfda95734697e8b8e8b9R1-R96) …

feat(playground): refactoring file uploader and voice recorder.

---

packages/agent/src/factory/createAutoBeApplication.ts
packages/agent/src/orchestrate/analyze/orchestrateAnalyzeReviewer.ts
packages/agent/src/orchestrate/analyze/orchestrateAnalyzeScenario.ts
packages/agent/src/orchestrate/analyze/orchestrateAnalyzeWrite.ts
packages/agent/src/orchestrate/interface/orchestrateInterfaceAuthorization.ts
packages/agent/src/orchestrate/interface/orchestrateInterfaceComplement.ts
packages/agent/src/orchestrate/interface/orchestrateInterfaceEndpoints.ts
packages/agent/src/orchestrate/interface/orchestrateInterfaceSchemas.ts
packages/agent/src/orchestrate/prisma/orchestratePrismaComponent.ts
packages/agent/src/orchestrate/prisma/orchestratePrismaCorrect.ts
packages/agent/src/orchestrate/prisma/orchestratePrismaReview.ts
packages/agent/src/orchestrate/realize/orchestrateRealizeAuthorization.ts
packages/agent/src/orchestrate/realize/orchestrateRealizeAuthorizationCorrect.ts
packages/agent/src/orchestrate/realize/orchestrateRealizeCoder.ts
packages/agent/src/orchestrate/test/experimental/orchestrateTestCorrect.ast
packages/agent/src/orchestrate/test/orchestrateTestCorrect.ts
packages/agent/src/orchestrate/test/orchestrateTestWrite.ts

`reference` becomes true until recent `@samchon/openapi`

fix(agent): no more reference option require for AI schemas.

---

packages/playground-ui/src/movies/chat/AutoBePlaygroundChatUploadMovie.tsx
packages/playground-ui/src/utils/AutoBePlaygroundFileUploader.ts

This pull request significantly improves file upload validation and user feedback in the playground chat upload component. The main changes introduce stricter file extension checks, better error reporting for unsupported file types, and enhancements to how file content is processed and encoded.
**File validation and user feedback improvements:**
* Added a comprehensive file extension validation system in `AutoBePlaygroundFileUploader`, restricting uploads to supported formats based on category (image, audio, video, document) and the presence of the file upload API. The supported formats are now explicitly defined in a `FORMATS` map. (`packages/playground-ui/src/utils/AutoBePlaygroundFileUploader.ts` [[1]](diffhunk://#diff-c46f6b4f855cf8bf230b09513fd82dbac0870ae8403acfda95734697e8b8e8b9R11- …

fix(playground): exact supported extensions

---

packages/agent/src/AutoBeAgent.ts
packages/agent/src/AutoBeMockAgent.ts
packages/agent/src/factory/createAutoBeContext.ts
packages/interface/src/events/AutoBeEvent.ts
packages/interface/src/events/AutoBeEventSource.ts
packages/interface/src/events/AutoBeRequestEvent.ts
packages/interface/src/events/AutoBeVendorRequestEvent.ts
packages/interface/src/events/AutoBeVendorResponseEvent.ts
packages/playground-ui/src/movies/events/AutoBePlaygroundEventMovie.tsx
test/src/features/typings/test_typing_rpc_listener_functions.ts

This pull request introduces a new system for tracking AI vendor requests and responses throughout the AutoBE backend generation workflow. It adds two new event types—`vendorRequest` and `vendorResponse`—with corresponding event interfaces, updates the event system to emit and handle these events, and refines event source documentation and usage. These changes provide more granular monitoring and attribution of AI usage, enabling improved debugging, cost analysis, and performance tracking.
**New AI Vendor Event Types and Interfaces:**
- Added `AutoBeVendorRequestEvent` and `AutoBeVendorResponseEvent` interfaces to represent requests sent to and responses received from the AI vendor (OpenAI), including full request/response payloads, streaming support, and source attribution. …

feat(interface): vendor request/response events

---

packages/vscode-extension/interface/src/message.dto/get-session-detail.dto.ts
packages/vscode-extension/interface/src/message.dto/get-session-list.dto.ts
packages/vscode-extension/interface/src/message.dto/index.ts
packages/vscode-extension/interface/src/message.dto/remove-session.dto.ts
packages/vscode-extension/src/core/autobe.ts
packages/vscode-extension/src/core/webview.ts
packages/vscode-extension/webview-ui/src/pages/Chat.tsx

- Introduced new DTOs: IRequestGetSessionDetail, IResponseGetSessionDetail, IRequestGetSessionList, IResponseGetSessionList, and IRequestRemoveSession for session management.
- Updated AutoBeWrapper to handle session retrieval and removal requests, enhancing session management capabilities.
- Modified webview components to support session listing and detail retrieval, improving user interaction with chat sessions.
---
This pull request adds support for session management in the VSCode extension, allowing users to view, select, and delete chat sessions from the UI. It introduces new message types and DTOs for session operations, updates the backend logic to handle these requests, and enhances the frontend to display and interact with session data.
**Session Management API and Backend …

feat(vscode-extension): add session management DTOs and update AutoBeWrapper

---

packages/vscode-extension/webview-ui/src/components/Movie/ChatMovie.tsx
packages/vscode-extension/webview-ui/src/components/Movie/events/AutoBeEventsMovie.tsx

- Enhanced ChatMovie component to filter out consecutive duplicate progress events for cleaner log display.
- Exported isAutoBeProgressEventBase function for better accessibility in event handling.
---
This pull request introduces improvements to the event handling logic in the `ChatMovie` component, specifically by filtering and compacting consecutive progress events to reduce redundancy in the event log display. Additionally, it makes the `isAutoBeProgressEventBase` helper function available for use outside its original file.
Event filtering and display improvements:
* Added logic in `ChatMovie.tsx` to filter out consecutive progress events of the same type, resulting in a more concise event log for users.
* Updated the event log construction in `ChatMovie.tsx` to use the filtered …

feat(vscode-extensions): optimize event logging by filtering duplicate progress events

---

packages/agent/prompts/ANALYZE_REVIEW.md
packages/agent/prompts/ANALYZE_WRITE.md
packages/agent/prompts/INTERFACE_AUTHORIZATION.md
packages/agent/prompts/INTERFACE_COMPLEMENT.md
packages/agent/prompts/INTERFACE_ENDPOINT.md
packages/agent/prompts/INTERFACE_GROUP.md
packages/agent/prompts/INTERFACE_OPERATION.md
packages/agent/prompts/INTERFACE_OPERATION_REVIEW.md
packages/agent/prompts/INTERFACE_SCHEMA.md
packages/agent/prompts/INTERFACE_SCHEMA_REVIEW.md
packages/agent/prompts/PRISMA_COMPONENT.md
packages/agent/prompts/PRISMA_CORRECT.md
packages/agent/prompts/PRISMA_REVIEW.md
packages/agent/prompts/PRISMA_SCHEMA.md
packages/agent/prompts/REALIZE_AUTHORIZATION.md
packages/agent/prompts/REALIZE_AUTHORIZATION_CORRECT.md
packages/agent/prompts/REALIZE_CODER.md
packages/agent/prompts/TEST_CORRECT.md
packages/agent/prompts/TEST_SCENARIO.md
packages/agent/prompts/TEST_WRITE.md

This pull request standardizes the formatting of the **REQUIRED ACTIONS** section across all agent prompt templates. The main change is moving the REQUIRED ACTIONS section above the PROHIBITED ACTIONS section and ensuring consistent formatting and emphasis in each file. This improves clarity and consistency for anyone updating or reading these prompts.
Prompt formatting and consistency improvements:
* Moved the **REQUIRED ACTIONS** section above **PROHIBITED ACTIONS** and ensured consistent formatting (e.g., bullet points, emphasis) in all agent prompt markdown files, such as `ANALYZE_REVIEW.md`, `ANALYZE_WRITE.md`, `INTERFACE_AUTHORIZATION.md`, `INTERFACE_COMPLEMENT.md`, `INTERFACE_ENDPOINT.md`, `INTERFACE_GROUP.md`, `INTERFACE_OPERATION.md`, `INTERFACE_OPERATION_REVIEW.md`, …

feat(agent): reverse what to do and not to do

---

packages/agent/src/orchestrate/interface/orchestrateInterface.ts

This pull request refactors how operations are collected and deduplicated in the `orchestrateInterface` function, and improves the way schemas are merged into the OpenAPI document. The changes focus on ensuring unique operations based on endpoint and method, and on more robustly merging schema components.
* Replaces the previous approach of simply pushing authorizations into the operations array with a new deduplication mechanism using a `HashMap` keyed by endpoint path and method, leveraging `AutoBeEndpointComparator` to ensure uniqueness. The result is a list of operations with duplicates removed, where earlier entries are preserved. (`packages/agent/src/orchestrate/interface/orchestrateInterface.ts`) [[1]](diffhunk://#diff-9011b0c160648b4ccca5ed6c13b2bff42bfd46562d883e13b90885f3e3dcd84e …

fix(agent): block duplicated operation

---

packages/agent/src/orchestrate/analyze/histories/transformAnalyzeReviewerHistories.ts
packages/agent/src/orchestrate/analyze/histories/transformAnalyzeWriteHistories.ts
packages/agent/src/orchestrate/analyze/orchestrateAnalyzeReview.ts
packages/agent/src/orchestrate/analyze/orchestrateAnalyzeWrite.ts

Forward user utterances to any agent within the anyze.

refactor(agent): update context usage in transformAnalyze functions

---

apps/playground-ui/src/movies/events/AutoBePlaygroundCompleteEventMovie.tsx

- Simplified file retrieval by introducing a reusable getFiles function for both PostgreSQL and SQLite.
- Removed redundant Singleton instances for file fetching, enhancing code clarity and maintainability.
- Updated the openStackBlitz function to utilize the new getFiles function for improved performance.

feat(playground-ui): refactor file retrieval logic in AutoBePlaygroundCompleteEventMovie

---

packages/agent/src/orchestrate/analyze/orchestrateAnalyze.ts
packages/agent/src/orchestrate/analyze/orchestrateAnalyzeReview.ts
packages/agent/src/orchestrate/analyze/orchestrateAnalyzeWrite.ts
packages/agent/src/orchestrate/interface/orchestrateInterfaceAuthorizations.ts
packages/agent/src/orchestrate/interface/orchestrateInterfaceEndpoints.ts
packages/agent/src/orchestrate/interface/orchestrateInterfaceSchemas.ts
packages/agent/src/orchestrate/interface/orchestrateInterfaceSchemasReview.ts
packages/agent/src/orchestrate/realize/orchestrateRealize.ts
packages/agent/src/orchestrate/realize/orchestrateRealizeAuthorization.ts
packages/agent/src/orchestrate/realize/orchestrateRealizeWrite.ts
packages/agent/src/orchestrate/test/orchestrateTestWrite.ts
test/src/features/realize/internal/validate_agent_realize_write.ts

This pull request refactors how progress and event IDs are generated across multiple orchestration modules in the agent package. Previously, IDs were generated at the orchestration level and passed down through function calls; now, each event is assigned a unique ID at the point of creation using `v7()` from the `uuid` library. This change simplifies function signatures, reduces unnecessary parameter passing, and ensures better uniqueness and traceability for events.
**Event ID Generation Refactor**
* All orchestration and event creation functions (`orchestrateAnalyzeWrite`, `orchestrateAnalyzeReview`, `orchestrateInterfaceAuthorizations`, `orchestrateInterfaceEndpoints`, `orchestrateInterfaceSchemas`, `orchestrateInterfaceSchemasReview`, `orchestrateRealizeWrite`, …

feat(agent): replace string IDs with v7 UUIDs in orchestrate functions 

---

packages/agent/prompts/INTERFACE_OPERATION.md
packages/agent/src/orchestrate/interface/orchestrateInterfaceOperationsReview.ts
packages/agent/src/orchestrate/interface/structures/IAutoBeInterfaceOperationsReviewApplication.ts
packages/interface/src/openapi/AutoBeOpenApi.ts
test/src/features/compiler/test_compiler_realize_controller.ts

If there is anything that implies soft delete, check that you have filled in prisma_schema, model_name, and soft_delete_column.

feat: Enhance soft delete validation and add model_name and soft_delete_column

---

apps/playground-ui/src/movies/chat/AutoBePlaygroundChatBodyMovie.tsx
apps/playground-ui/src/movies/chat/AutoBePlaygroundChatMovie.tsx
packages/ui/src/AutoBeChatMain.tsx
packages/ui/src/banner/AutoBeChatBanner.tsx
packages/ui/src/banner/AutoBeChatState.tsx
packages/ui/src/constant/color.ts
packages/ui/src/index.ts

- Introduced AutoBeChatState component to display chat state information.
- Updated AutoBeChatBanner to include chat state as a collapsible section.
- Modified AutoBePlaygroundChatMovie to pass listener state to AutoBeChatMain.
- Refactored interfaces and imports for better organization and clarity.
---

feat(ui): enhance chat components with AutoBeChatState and state management

---

packages/agent/build/prompt.ts
packages/agent/src/AutoBeAgent.ts
packages/agent/src/constants/AutoBeConfigConstant.ts
packages/agent/src/context/AutoBeContext.ts
packages/agent/src/context/AutoBeTokenUsageComponent.ts
packages/agent/src/factory/consentFunctionCall.ts
packages/agent/src/factory/createAutoBeContext.ts
packages/agent/src/orchestrate/interface/orchestrateInterfaceComplement.ts
packages/agent/src/orchestrate/interface/orchestrateInterfaceOperations.ts
packages/agent/src/orchestrate/interface/orchestrateInterfaceSchemas.ts
packages/agent/src/orchestrate/prisma/orchestratePrismaCorrect.ts
packages/agent/src/orchestrate/realize/orchestrateRealizeAuthorizationCorrect.ts
packages/agent/src/orchestrate/test/orchestrateTestCorrect.ts
packages/agent/src/structures/IAutoBeConfig.ts

This pull request introduces a unified and configurable retry mechanism across the agent's orchestration and context logic. The most significant change is the addition of a `retry` parameter (defaulting to 4) in the agent configuration and context, which is now consistently used throughout the orchestration and factory functions. This improves reliability and makes the retry behavior easily adjustable.
**Retry Configuration and Propagation:**
* Introduced `retry` as an optional parameter in `IAutoBeConfig`, with a default value of 4, and created a new `AutoBeConfigConstant` to hold the default. This value is now propagated into the agent's context and used throughout orchestration logic. [[1]](diffhunk://#diff-ca7d501ea1bf6478bffff9779e7c688234ba8cdbef68180f7f49670d0120a33bR19-R21) …

feat(agent): global retry count configuration

---

packages/agent/src/orchestrate/interface/orchestrateInterface.ts
packages/agent/src/orchestrate/interface/orchestrateInterfaceSchemas.ts
packages/agent/src/orchestrate/interface/orchestrateInterfaceSchemasReview.ts
packages/agent/src/orchestrate/interface/structures/authTokenSchema.ts
packages/agent/src/orchestrate/realize/orchestrateRealizeCorrect.ts

This pull request refactors and improves the orchestration of interface schema generation and review in the agent package. The main focus is on separating the review logic, enhancing schema validation, and improving maintainability by moving shared structures to dedicated files. There are also improvements in how authorization token schemas are handled and validated.
**Schema orchestration and review process:**
* Refactored the orchestration flow in `orchestrateInterface` to call `orchestrateInterfaceSchemasReview` after complementing schemas, ensuring reviewed schemas are merged into the final OpenAPI document. [[1]](diffhunk://#diff-9011b0c160648b4ccca5ed6c13b2bff42bfd46562d883e13b90885f3e3dcd84eR23) [[2]](diffhunk://#diff-9011b0c160648b4ccca5ed6c13b2bff42bfd46562d883e13b90885f3e3dcd84eL …

feat(agent): Modify the component to be followed by a schema review

---

packages/agent/prompts/TEST_SCENARIO.md
packages/agent/prompts/TEST_WRITE.md
packages/agent/src/orchestrate/test/histories/transformTestScenarioHistories.ts
packages/compiler/src/realize/testRealizeProject.ts

This pull request primarily updates the `TEST_SCENARIO.md` documentation to clarify that test scenarios must be based strictly on the provided API operations array, not on backend implementation details or schema fields. It also makes a minor formatting improvement in `transformTestScenarioHistories.ts` and changes the worker connector mode in `testRealizeProject.ts` from "thread" to "process".
**Documentation clarity and rule enforcement:**
* Updated all references in `TEST_SCENARIO.md` to prohibit inferring API availability or functionality from backend implementation details, not just schema fields. This includes rules, prohibitions, examples, and checklist items. [[1]](diffhunk://#diff-90a27798de686eeef98ffdc6119064f6316477e75317e8f0d502549b5ce84d0fL264-R270) …

fix(agent): hallucination test scenario prompt

---

packages/agent/prompts/TEST_CORRECT.md
packages/agent/prompts/TEST_SCENARIO.md
packages/agent/prompts/TEST_WRITE.md
packages/agent/src/orchestrate/test/histories/transformTestScenarioHistories.ts
packages/agent/src/orchestrate/test/orchestrateTestScenario.ts
packages/agent/src/orchestrate/test/structures/IAutoBeTestCorrectApplication.ts
packages/agent/src/orchestrate/test/structures/IAutoBeTestWriteApplication.ts

This pull request introduces significant improvements to both the test scenario orchestration and the diagnostic analysis workflows. The most notable changes include the addition of automated candidate dependency analysis for API test scenarios, refactoring to consistently use the full OpenAPI document for scenario generation, and a major update to how TypeScript compilation diagnostics are summarized and presented. These enhancements improve the clarity, reliability, and usefulness of generated test plans and diagnostic outputs.
**Test Scenario Orchestration Improvements**
* Added automated candidate dependency analysis: The system now analyzes all API operations to identify fields ending with `_id` in path parameters and request bodies, generating a "candidate dependencies" table to …

feat(test): add candidate dependencies

---

apps/hackathon-server/src/providers/sessions/acceptors/AutoBeHackathonSessionSocketAcceptor.ts

This pull request refactors the replay logic in the `AutoBeHackathonSessionSocketAcceptor` namespace to improve how session histories and event snapshots are retrieved and returned. The main change is to return both histories and snapshots together, rather than just snapshots, which enables more flexible handling of session data during replay.
**Refactoring of replay logic:**
* The `startReplay` function now returns an object containing both `histories` and `snapshots` instead of just `snapshots`, allowing consumers to access both sets of data for session replay. [[1]](diffhunk://#diff-dc176e465211555f56089aa23f94c75a26b7993bd3b8890adf7757d72e0b6f8eL90-R99) [[2]](diffhunk://#diff-dc176e465211555f56089aa23f94c75a26b7993bd3b8890adf7757d72e0b6f8eL139-R140)
* The calling code is updated to …

fix(hackathon): block polling when no history at all

---

test/.gitignore
test/package.json
test/src/archive/commit.ts
test/src/internal/TestHistory.ts

This pull request introduces a new script for archiving commits and refines the handling of repository and history files in the test suite. The most notable changes are the addition of the `archive:commit` script and improvements to phase management in history-related utilities.
**New Commit Archiving Functionality:**
* Added a new script `archive:commit` to `package.json`, which runs the newly introduced `src/archive/commit.ts` file for archiving generated files to specific repositories.
* Implemented `src/archive/commit.ts`, which automates cloning, updating, and pushing changes to example repositories for different vendors and projects. This script uses the latest generated files from the agent and handles the commit/push workflow.
**Repository and File Management Improvements:**
* …

feat(test): automatic example commit system

---

packages/agent/prompts/INTERFACE_GROUP.md
packages/agent/src/orchestrate/interface/structures/IAutoBeInterfaceGroupApplication.ts
test/src/executable/endpoints.ts

This pull request refactors how interface group descriptions are defined and documented, focusing on making them shorter and more direct. It also adds a utility test for decompressing and reading group data. The most important changes are grouped below:
**Documentation and Schema Definition Simplification:**
* Updated group descriptions in `packages/agent/prompts/INTERFACE_GROUP.md` to be concise and focused, replacing detailed paragraphs with brief statements of core purpose and main entities.
* Revised the group description requirements in `INTERFACE_GROUP.md` to require short, essential information (50-200 characters) and removed the need for detailed schema mappings or lengthy explanations.
* Simplified the `description` field in the `IAutoBeInterfaceGroupApplication` TypeScript …

feat(agent): make interface group description concisely.

---

packages/agent/prompts/INTERFACE_SCHEMA.md
packages/agent/prompts/INTERFACE_SCHEMA_REVIEW.md

This pull request strengthens the security and data consistency requirements for API interface schemas by updating documentation and review checklists. The changes clarify how to correctly handle password fields, timestamp fields, and the mapping of database schema properties, ensuring that all interface schemas are both secure and accurately reflect the underlying Prisma database. The updates also introduce new error checks and quality assurance steps for schema reviews.
**Security and Data Consistency Enforcement**
* Added explicit guidelines and checklist items to ensure every property in interface schemas exists in the actual Prisma schema, with special emphasis on verifying timestamp fields like `created_at`, `updated_at`, and `deleted_at` per table. …

feat(agent): no hashed password request and none-existing timestamps.

---

website/src/movies/landing/AutoBeLandingDemoMovie.tsx

This pull request updates the model selection UI in the `AutoBeLandingDemoMovie` component to simplify the user experience. Instead of using a tab-based interface with sliding background indicators, the model selection is now presented as a dropdown menu.
**UI Improvements:**
* Replaced the tab-based model selection interface with a simpler dropdown menu for choosing AI models in `AutoBeLandingDemoMovie.tsx`. This makes the selection more accessible and easier to use, especially on smaller screens.

feat(website): combobox on replay model selector

---

website/src/content/docs/hackathon/index.mdx
website/src/content/docs/index.mdx
website/src/content/docs/roadmap/v1.0.mdx
website/src/content/tutorial/hackathon/index.mdx
website/src/data/AutoBeDemoStorage.ts
website/src/movies/demo/AutoBeDemoModelMovie.tsx
website/src/movies/demo/AutoBeDemoMovie.tsx
website/src/movies/demo/AutoBeDemoProjectMovie.tsx
website/src/movies/landing/AutoBeLandingDemoMovie.tsx
website/src/movies/landing/AutoBeLandingMovie.tsx

This pull request refactors the demo movie components used to showcase AutoBE's AI model capabilities across the documentation and landing pages. The changes consolidate and rename components for clarity, improve code organization, and enhance UI responsiveness. The most important changes are grouped below.
**Component Refactoring and Renaming**
* Renamed `AutoBeLandingDemoModelMovie` to `AutoBeDemoModelMovie` and moved it from `movies/landing` to `movies/demo` for better clarity and separation of concerns. All usages in documentation files were updated to use the new import path and name. [[1]](diffhunk://#diff-a68feff51cee391d63ee861d2e22b7faaaad3f6c1e7e76a502e634f9a55004f3L3-R3) [[2]](diffhunk://#diff-a68feff51cee391d63ee861d2e22b7faaaad3f6c1e7e76a502e634f9a55004f3L133-R141) …

feat(website): refactor demo content

---

website/src/movies/demo/AutoBeDemoModelMovie.tsx
website/src/movies/demo/AutoBeDemoMovie.tsx
website/src/movies/landing/AutoBeLandingMovie.tsx

This pull request introduces minor UI improvements to the movie demo components, focusing on better spacing and layout responsiveness for smaller screens.
UI and layout enhancements:
* Reduced horizontal padding in the main section from `px-6` to `px-2 sm:px-6` in `AutoBeDemoMovie`, making the layout more mobile-friendly.
* Adjusted grid gap from `gap-6` to `gap-3 sm:gap-6` and removed inline max-width and margin styles in `AutoBeDemoModelMovie` to improve spacing and simplify layout control.
* Simplified the model selection dropdown container by removing unnecessary flex alignment and gap, resulting in a cleaner UI.

fix(website): landinig page layout
