wrtnlabs/autobe

packages/compiler/package.json, packages/compiler/src/AutoBePrismaCompiler.ts, packages/interface/src/compiler/IAutoBePrismaCompilerResult.ts, pnpm-lock.yaml, pnpm-workspace.yaml, test/src/features/compiler/test_compiler_facade_bbs.ts, test/src/features/compiler/test_compiler_facade_shopping.ts, test/src/features/compiler/test_compiler_prisma_correct.ts, test/src/features/compiler/test_compiler_prisma_failure.ts, test/src/features/compiler/test_compiler_typescript_failure.ts, test/src/features/compiler/test_compiler_typescript_fs.ts, test/src/features/compiler/test_compiler_typescript_migrate.ts
Related PR: samchon/prisma-markdown#33
-----------
This pull request introduces the integration of the `prisma-markdown` library into the `AutoBePrismaCompiler`, adds diagram generation functionality, and updates test cases to include additional validation using the `typia` library. It also updates dependencies in the `pnpm-lock.yaml` file to support these changes.
* Added the `prisma-markdown` library as a dependency in `package.json` and `pnpm-lock.yaml` for diagram generation functionality. (`[[1]](diffhunk://#diff-11f1c967e7b88e8bb1ad9292bc77da6ad6ac034c264ce56eed069eb1e19865deR22)`, `[[2]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR27-R29)`, `[[3]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR1475-R1491)`)
* …
=> Add ERDs on prisma compiler result

.github/workflows/release.yml, package.json, pnpm-lock.yaml
This pull request introduces a release workflow, updates dependencies, and adds configuration for changelog generation and version bumping. The key changes include the addition of a GitHub Actions workflow for publishing and releasing, the integration of the `bumpp` package for version management, and updates to the `pnpm-lock.yaml` file to include new dependencies.
- Added a new GitHub Actions workflow in `.github/workflows/release.yml` to automate publishing to NPM and generating changelogs. This includes steps for setting up Node.js, installing dependencies with `pnpm`, and publishing the package with provenance enabled.
- Updated `package.json` to include `bumpp` (v10.1.1) for version bumping and added a `release` script. Also configured `changelogithub` to categorize changes into …
=> ci: introduce bumpp for deploy pacakges

packages/agent/src/orchestrate/orchestrateAnalyze.ts
This pull request updates the `orchestrateAnalyze` function to improve state management and ensure analysis history is properly recorded.
State management improvements:
* [`packages/agent/src/orchestrate/orchestrateAnalyze.ts`](diffhunk://#diff-0760076d2713c7b74179a23fe6dfd2a97aa15f908f6752174db0d94d521dc9bcR64-R71): Added a call to `ctx.histories().push(history)` to append the analysis history to the histories array and updated `ctx.state().analyze` to store the current analysis history.
=> fix(agent): state and history dispatching

packages/rpc/src/AutoBeRpcService.ts
This pull request updates the imports in the `AutoBeRpcService.ts` file to improve module resolution and align with the updated package structure.
* Changed the import path for `AutoBeAgent` to use the `@autobe/agent` package instead of a relative path, ensuring consistency with the updated module structure. [[1]](diffhunk://#diff-a04b770e10e58fd0b8b9115520a1975a142da73faa9b6d5c2e39ae7b8770eb59R1) [[2]](diffhunk://#diff-a04b770e10e58fd0b8b9115520a1975a142da73faa9b6d5c2e39ae7b8770eb59L10-L11)
=> fix(rpc): wrong import path

packages/rpc/src/AutoBeRpcService.ts
This pull request introduces additional event listeners to the `AutoBeRpcService` class to handle new Prisma-related events. These changes expand the service's capabilities for managing Prisma components and schemas.
Enhancements to event handling:
* [`packages/rpc/src/AutoBeRpcService.ts`](diffhunk://#diff-a04b770e10e58fd0b8b9115520a1975a142da73faa9b6d5c2e39ae7b8770eb59R43-R48): Added new event listeners for `prismaComponents` and `prismaSchemas` to invoke corresponding methods on the `listener` object. These additions complement the existing Prisma-related events (`prismaStart` and `prismaComplete`) for more comprehensive event handling.
=> fix(rpc): event tracing on RpcService

pnpm-lock.yaml, pnpm-workspace.yaml
This pull request updates dependency versions across multiple files to replace specific development versions with stable semantic versions for the `@nestia` package suite. The changes ensure consistency and maintainability by adopting a standardized versioning format.
* **`pnpm-lock.yaml`:**
- Updated `@nestia/core`, `@nestia/e2e`, and `@nestia/migrate` dependencies from `7.0.0-dev.20250608` to `7.0.0` in various sections (`catalogs`, `importers`, `packages`, and `snapshots`). This includes both the version specifiers and resolution integrity hashes. [[1]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL18-R25) [[2]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL174-R177) …
=> feat(compiler): bump up nestia dependencies

website/pages/docs/roadmap/beta.mdx, website/pages/docs/websocket/index.mdx, website/template/AutoBeRoadmapPreface.mdx
This pull request introduces updates to documentation and project planning, focusing on enhancing roadmap clarity, adding new features, and providing detailed technical explanations. Key changes include the introduction of snapshot logic in the roadmap, a detailed explanation of an RPC-based WebSocket implementation, and updates to the Gantt chart timeline.
* Updated the roadmap in `website/pages/docs/roadmap/beta.mdx` to include a new "Snapshot Logic" section under "3.2. Snapshot Logic," detailing the implementation of comprehensive validation mechanisms for OpenAPI documents, SDKs, and database schema definitions.
* Added "Snapshot Logic" as a planned task in the Gantt chart for the Interface Agent, scheduled for June 2025.
* Added a new section in …
=> feat(website): add snapshot plan

packages/agent/prompts/TEST.md, packages/agent/src/orchestrate/analyze/AutoBeAnalyzeAgent.ts, packages/agent/src/orchestrate/analyze/AutoBeAnalyzeReviewer.ts, packages/agent/src/orchestrate/analyze/orchestrateAnalyze.ts, packages/agent/src/orchestrate/test/orchestrateTestScenario.ts, packages/agent/src/orchestrate/test/transformTestScenarioHistories.ts, test/src/features/test/internal/validate_agent_test_schenario.ts, test/src/features/test/test_agent_test_scenario_bbs.ts
To prevent agents from writing more than 10 meaningless test codes, even in simple object return APIs, we have modified the prompts to provide a wealth of information from proposals to schema information, and to focus on quality rather than quantity in consideration of business value.
=> Consider business value when writing test scenarios

pnpm-lock.yaml, website/package.json
This pull request introduces the `pagefind` library to enhance search functionality on the website. It updates dependencies, modifies build scripts, and integrates optional platform-specific packages for `pagefind`.
* Added `pagefind` as a dependency in `website/package.json` and updated the `postbuild` script to include a `build:pagefind` step for generating search indexes. (`[[1]](diffhunk://#diff-fae242fbf77a8a9d52625664bc36ea12316586f8a716b41137d897a2b7e3df76L9-R11)`, `[[2]](diffhunk://#diff-fae242fbf77a8a9d52625664bc36ea12316586f8a716b41137d897a2b7e3df76R40)`)
* Added platform-specific optional dependencies for `pagefind` (`@pagefind/darwin-arm64`, `@pagefind/darwin-x64`, `@pagefind/linux-arm64`, `@pagefind/linux-x64`, `@pagefind/windows-x64`) in `pnpm-lock.yaml` to support various …
=> feat(website): pagefind

packages/agent/src/orchestrate/interface/orchestrateInterfaceComplement.ts, packages/agent/src/orchestrate/prisma/orchestratePrismaCorrect.ts, packages/agent/src/orchestrate/test/orchestrateTestCorrect.ts
This pull request updates the `orchestratePrismaCorrect` function in `packages/agent/src/orchestrate/prisma/orchestratePrismaCorrect.ts` to improve clarity and handle failure cases more explicitly. The most important changes include renaming a parameter for better readability, updating references to the renamed parameter, and adding a failure condition when retries are exhausted.
* Renamed the `retry` parameter to `life` in the `orchestratePrismaCorrect` function to better reflect its purpose. Updated all references to this parameter accordingly. [[1]](diffhunk://#diff-ef86dd4305e40242004412ee7909671fd0ffa7985080fe9b62574ab1f1b0fdafL14-R14) [[2]](diffhunk://#diff-ef86dd4305e40242004412ee7909671fd0ffa7985080fe9b62574ab1f1b0fdafL24-R24)
* Added a new condition in the `step` function to …
=> fix(agent): life checking on prisma corrector.

packages/compiler/src/AutoBeTypeScriptCompiler.ts, test/src/features/compiler/test_compiler_typescript_alias.ts
This pull request includes changes to the `AutoBeTypeScriptCompiler` implementation and introduces new test coverage for TypeScript alias imports. The most significant updates involve removing the `nestiaCoreTransform` dependency, updating compiler options, and adding a new test to validate TypeScript alias behavior.
* Removed the `nestiaCoreTransform` dependency from the imports and the `transformers` array, simplifying the compiler's setup. (`packages/compiler/src/AutoBeTypeScriptCompiler.ts`) [[1]](diffhunk://#diff-cad54d4ee71a3f3f3d525f73ad52fb3d133c03bb52d73b2812dfd8aaf4bfd481L6) [[2]](diffhunk://#diff-cad54d4ee71a3f3f3d525f73ad52fb3d133c03bb52d73b2812dfd8aaf4bfd481L69-L75)
* Updated the `paths` configuration in the `compilerOptions` to include a `baseUrl` and adjusted alias mappings …
=> fix(compiler): paths with baseUrl

packages/interface/src/rpc/IAutoBeRpcVendor.ts, packages/playground-server/src/executable/server.ts, packages/playground-ui/src/movies/chat/AutoBePlaygroundChatSideMovie.tsx, packages/playground-ui/src/movies/configure/AutoBePlaygroundConfigureMovie.tsx, packages/playground-ui/src/movies/configure/AutoBePlaygroundConfigureVendorMovie.tsx
This pull request introduces a new `semaphore` property to the `IAutoBeRpcVendor` interface and integrates it across the application to manage the concurrency level for API requests. The changes ensure that the `semaphore` value is configurable, displayed in the UI, and passed correctly through the system.
* **`IAutoBeRpcVendor` interface**: Added the `semaphore` property to specify the maximum number of concurrent API requests. Includes detailed documentation and a default value of 16. (`packages/interface/src/rpc/IAutoBeRpcVendor.ts`, [packages/interface/src/rpc/IAutoBeRpcVendor.tsR60-R80](diffhunk://#diff-e05ebd6a22410f2b4f0ffe66e4dbf532fa046360706ed8b92c493a09b9158e56R60-R80))
* **Server configuration**: Updated the `server.ts` file to pass the `semaphore` value from the vendor …
=> feat(playground): add semaphore input

packages/agent/src/AutoBeAgent.ts, packages/agent/src/orchestrate/test/orchestrateTestCorrect.ts
This pull request introduces several changes to improve type safety and simplify logic in the `AutoBeAgent` and `orchestrateTestCorrect` components. The main updates include replacing implicit type inference with explicit type annotations, simplifying conditional statements, and improving code readability.
* Added explicit type annotations to variables such as `scenarioMap`, `testFiles`, `retainedFiles`, `mergedFiles`, and `files` in `orchestrateTestCorrect` to ensure type safety and clarify the expected data structures. [[1]](diffhunk://#diff-884758dfb882ce4573dac533bfef2f812d974b58bd7bd9a384ddb3cb7f47ffd9L26-R32) [[2]](diffhunk://#diff-884758dfb882ce4573dac533bfef2f812d974b58bd7bd9a384ddb3cb7f47ffd9L41-R43) [[3]](diffhunk://#diff-884758dfb882ce4573dac533bfef2f812d974b58bd7bd9a384ddb3cb7f …
=> feat(agent): enforce file generation even compilation failed

packages/agent/src/AutoBeAgent.ts
This pull request makes a small addition to the `AutoBeAgent` class in `packages/agent/src/AutoBeAgent.ts`. It introduces a new `tokenUsage` property to the `AutoBeAgent` configuration.
* [`packages/agent/src/AutoBeAgent.ts`](diffhunk://#diff-eb5845bde058399222e7eb37fcc40ccd00bee27a5d2531830decea25dc197e73R127): Added `tokenUsage` to the `AutoBeAgent` class to allow tracking or configuration related to token usage.
=> fix: use external tokenUsage

pnpm-lock.yaml, pnpm-workspace.yaml
This pull request updates the `@agentica/core` and `@agentica/rpc` dependencies to version `0.30.2` across the project configuration files. These changes ensure compatibility with the latest features and improvements of the `agentica` libraries.
Dependency version updates:
* [`pnpm-lock.yaml`](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL10-R11): Updated `@agentica/core` dependency from `0.30.1` to `0.30.2` in multiple sections, including `settings`, `importers`, `packages`, and `snapshots`. This includes updating the integrity hash for the new version. [[1]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL10-R11) [[2]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL156-R156) …
=> fix(agent): bug of function-calling validate-feedback

README.md, website/src/template/AutoBePlaygroundSection.mdx
This pull request includes updates to external links and embedded media references in the project documentation and website.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L48-R48): Updated the playground asset URL to point to a new resource.
* [`website/src/template/AutoBePlaygroundSection.mdx`](diffhunk://#diff-f71dc825064691ee145ab5fa572685f1ac0674de00fa3d8faef39dfb1c93dbf3L3-R3): Changed the embedded YouTube video URL to a new demonstration video.
=> feat(website): change to new youtube video

internals/dependencies/nestjs/package-lock.json, internals/dependencies/nestjs/package.json, packages/agent/src/orchestrate/test/orchestrateTest.ts, test/src/features/test/internal/validate_agent_test_main.ts
This pull request includes updates to improve the test orchestration and logging mechanisms in the agent's codebase. The most important changes involve switching to a different compile method for TypeScript tests and modifying the structure of the logged result JSON to exclude files.
* [`packages/agent/src/orchestrate/test/orchestrateTest.ts`](diffhunk://#diff-da0f884d69cbd6a2950be9203925295ce405e2ab85d5e7ef37b3d7fbeb63eb3cL73-R73): Changed the method used for TypeScript test compilation from `compiler.test.compile` to `compiler.typescript.compile` for better alignment with the naming convention and functionality.
* [`test/src/features/test/internal/validate_agent_test_main.ts`](diffhunk://#diff-33d48b68dc459507466717f8cdc6de963d14b5c488f1b1730ea0eaaf60cf641fL58-R65): Updated the …
=> fix(agent): final compilation of test agent

packages/compiler/src/AutoBeTypeScriptCompiler.ts, packages/compiler/src/test/AutoBeTestCompiler.ts, packages/interface/src/compiler/IAutoBeTypeScriptCompileResult.ts, test/src/features/compiler/test_compiler_realize_files.ts, test/src/features/test/internal/validate_agent_test_correct.ts, test/src/features/test/internal/validate_agent_test_write.ts
This pull request refactors the TypeScript compilation process by modifying the handling of compilation results to simplify the output and improve error handling. The most notable changes include updating the `compile` method to return structured results, deprecating the inclusion of JavaScript output in the compilation result, and updating related test cases to reflect these changes.
* Updated the `compile` method in `AutoBeTypeScriptCompiler` and `AutoBeTestCompiler` to return structured results, differentiating between success, failure, and exception cases. This improves error handling and clarity. (`packages/compiler/src/AutoBeTypeScriptCompiler.ts`, `packages/compiler/src/test/AutoBeTestCompiler.ts`) [[1]](diffhunk://#diff-cad54d4ee71a3f3f3d525f73ad52fb3d133c03bb52d73b2812dfd8aaf4bfd4 …
=> feat(interface) remove compiled javascript files

test/src/features/compiler/test_compiler_test_build.ts
This pull request adds a new test function, `test_compiler_test_build`, to the `test/src/features/compiler/test_compiler_test_build.ts` file. The function integrates with the AutoBe framework to compile TypeScript files and validate the compilation result.
* **Added `test_compiler_test_build` function**:
- Imports necessary modules from the AutoBe framework, OpenAI, and other libraries.
- Retrieves test history using `TestHistory.getTest` and validates it with `typia.assert`.
- Initializes an `AutoBeAgent` configured with a ChatGPT model and a custom compiler.
- Merges files from the agent and test history, filtering for `.ts` files, and compiles them using the agent's TypeScript compiler.
- Validates the compilation result to ensure it matches the expected outcome ("success").
=> feat(test): build test of test agent result

packages/agent/src/orchestrate/prisma/orchestratePrismaSchema.ts, packages/interface/src/events/AutoBeEvent.ts, packages/interface/src/events/AutoBePrismaInsufficientEvent.ts, packages/interface/src/events/index.ts, packages/interface/src/rpc/IAutoBeRpcListener.ts, packages/playground-ui/src/movies/events/AutoBePlaygroundEventMovie.tsx, packages/playground-ui/src/movies/events/AutoBePlaygroundProgressEventMovie.tsx, packages/playground-ui/src/structures/AutoBePlaygroundListener.ts, test/src/features/prisma/internal/validate_agent_prisma_main.ts
This pull request introduces a retry mechanism for processing Prisma schema files and enhances logging in the Prisma validation tests. The changes improve the system's resilience and provide more detailed feedback during test execution.
* Added a `retryCount` parameter to the `process` function to limit retries to 3 attempts if processing fails. The retry logic uses a `forceRetry` wrapper to reattempt the operation. (`packages/agent/src/orchestrate/prisma/orchestratePrismaSchema.ts`, [[1]](diffhunk://#diff-a845895ec2d362db67d593064547c951226e4932be1fa43b640b89e335aa944aR60) [[2]](diffhunk://#diff-a845895ec2d362db67d593064547c951226e4932be1fa43b640b89e335aa944aL107-R110) [[3]](diffhunk://#diff-a845895ec2d362db67d593064547c951226e4932be1fa43b640b89e335aa944aR122-R123)
* Replaced the …
=> feat(agent): new event `AutoBePrismaInsufficientEvent`

packages/agent/src/orchestrate/analyze/orchestrateAnalyze.ts, packages/agent/src/orchestrate/analyze/writeDocumentUntilReviewPassed.ts, packages/interface/src/events/AutoBeAnalyzeWriteEvent.ts, pnpm-lock.yaml
This pull request introduces progress tracking for document analysis and updates dependencies in the project. The most significant changes include adding a progress object to track the status of document generation, modifying related functions to utilize this progress object, and upgrading the `@nestia` dependencies in the `pnpm-lock.yaml` file.
* Added a `progress` object to track the total and completed number of documents being analyzed. This includes updates to the `orchestrateAnalyze` function in `orchestrateAnalyze.ts` and the `writeDocumentUntilReviewPassed` function in `writeDocumentUntilReviewPassed.ts` to pass and update the `progress` object. [[1]](diffhunk://#diff-b9d5e2b6585091c8e6fdb8862e5794072327782b6dc63890e052a4c11166768bR73-R77) …
=> feat(agent): add total and completed count for analyze progress status

packages/filesystem/package.json, packages/filesystem/tsconfig.json
This pull request introduces changes to prepare the `filesystem` package for publication. The updates include specifying the files to be included in the package, configuring publishing options, and modifying TypeScript settings to generate output files.
* [`packages/filesystem/package.json`](diffhunk://#diff-8b4d86e418f80903f5df96d1057f4a5584307947d24b0dc96d4836c762278b76R21-R32): Added a `files` array to specify which files to include in the package, and a `publishConfig` object to set the package's publishing options, such as public access and entry points for JavaScript and TypeScript.
* [`packages/filesystem/tsconfig.json`](diffhunk://#diff-f15e1d8604bd7474d6ba12fd733aa3dde9f137495232767fba5a905d585650feL4-R4): Changed the `compilerOptions.noEmit` setting to `outDir: "lib"` to enable …
=> fix(filesystem): for npm publishing

packages/playground-ui/index.html, packages/playground-ui/replay.html, packages/playground-ui/src/movies/chat/AutoBePlaygroundChatMovie.tsx
This pull request introduces small changes to the `playground-ui` package to improve layout styling and functionality. The most important changes include adding inline styles to `body` tags for consistent margin and padding, adjusting the default height state in the chat movie component, and adding a `ref` to the `AppBar` component for future functionality.
* [`packages/playground-ui/index.html`](diffhunk://#diff-1895190307b91deb5670bb9d6035d572749c6c49280716709dc62c416827c5eaL11-R11): Added `margin: 0px` and `padding: 0px` styles to the `body` tag to ensure consistent layout.
* [`packages/playground-ui/replay.html`](diffhunk://#diff-5123afd92309186cc0fa19e23c2d1034d3fdba5e7c6ddecef2ca5ef509af607aL11-R11): Added `margin: 0px` and `padding: 0px` styles to the `body` tag to ensure …
=> feat(ui): remove margin and padding

packages/agent/src/orchestrate/realize/structures/IAutoBeRealizeCompile.ts, packages/agent/src/orchestrate/realize/writeCodeUntilCompilePassed.ts, packages/agent/src/utils/arrayToRecord.ts, test/src/features/realize/internal/validate_agent_realize_coder.ts
Created a new utility function that handles two common patterns for converting arrays to
Records:
1. Object array conversion: Extracts key-value pairs from objects using specified properties
arrayToRecord(items, "id", "value") // { [item.id]: item.value }
2. Entry array conversion: Directly converts [key, value][] arrays (e.g., from Object.entries)
arrayToRecord(Object.entries(obj)) // Reconstructs the object
Refactored existing code
- Replaced manual map + reduce patterns with arrayToRecord calls
- Simplified authorization payload processing
- Cleaned up file entries filtering and conversion
Benefits
- DRY principle: Eliminated duplicate array-to-Record conversion logic
- Type safety: Maintained full TypeScript type inference with generics
- Flexibility: Single function handles multiple …
=> refactor(agent): add comments and util function `arrayToRecord`

packages/agent/src/orchestrate/realize/writeCodeUntilCompilePassed.ts
filteting only provider files in `RealizeCoderAgent`
=> fix: filtering only provider functions

packages/agent/src/AutoBeAgent.ts
This pull request includes a small change to the `AutoBeAgent` class in `packages/agent/src/AutoBeAgent.ts`. The change updates the `tokenUsage` property to use `this.usage_.facade` instead of `props.tokenUsage?.facade`.
=> fix(agent): update tokenUsage assignment to use instance variable

CLAUDE.md
This pull request updates the licensing information in the `CLAUDE.md` file to reflect a change in the project's license.
* [`CLAUDE.md`](diffhunk://#diff-6ebdb617a8104a7756d0cf36578ab01103dc9f07e4dc6feb751296b9c402faf7L263-R263): Updated the license from MIT to AGPL 3.0 under the "Repository Information" section.
=> feat(*): fix license in CLAUDE.md

packages/agent/prompts/PRISMA_SCHEMA.md, packages/agent/src/orchestrate/prisma/orchestratePrismaSchemas.ts, packages/agent/src/orchestrate/prisma/structures/IAutoBePrismaSchemaApplication.ts, packages/interface/src/events/AutoBePrismaSchemasEvent.ts
This pull request refactors the Prisma schema generation process to use a 4-step workflow with AST (Abstract Syntax Tree) model representations instead of PSL (Prisma Schema Language) code strings. The changes affect both the agent prompt documentation and the TypeScript interface definitions, ensuring that all schema generation, review, and finalization steps operate on structured model objects. The process now emphasizes English-only descriptions, direct AST manipulation, and improved clarity in requirements.
**Refactor of Prisma Schema Generation Process:**
*Workflow and Structure Updates:*
- Changed the schema generation workflow from a 5-step process (including PSL code and a final AST transformation) to a streamlined 4-step process that works directly with AST model arrays …
=> feat(prisma): draft and final, all of them are AST.

CLAUDE.md, packages/agent/prompts/PRISMA_SCHEMA.md, packages/agent/src/context/AutoBeTokenUsage.ts, packages/agent/src/context/AutoBeTokenUsageComponent.ts, packages/agent/src/orchestrate/prisma/histories/transformPrismaSchemaHistories.ts, packages/agent/src/orchestrate/prisma/orchestratePrismaComponent.ts, packages/agent/src/orchestrate/prisma/orchestratePrismaCorrect.ts, packages/agent/src/orchestrate/prisma/orchestratePrismaSchemas.ts, packages/agent/src/orchestrate/prisma/structures/IAutoBePrismaSchemaApplication.ts, packages/interface/src/events/AutoBePrismaSchemasEvent.ts, test/src/TestFactory.ts, test/src/features/analyze/internal/validate_agent_analyze_main.ts, test/src/features/interface/internal/prepare_agent_interface.ts, test/src/features/interface/internal/validate_agent_interface_main.ts, test/src/features/prisma/internal/prepare_agent_prisma.ts, test/src/features/prisma/internal/validate_agent_prisma_main.ts, test/src/features/realize/internal/prepare_agent_realize.ts, test/src/features/realize/internal/validate_agent_realize_main.ts, test/src/features/test/internal/prepare_agent_test.ts, test/src/index.ts
This pull request streamlines and simplifies the Prisma schema generation process across the documentation, prompts, type definitions, and orchestration logic. The main change is a reduction from a 4-step (or 5-step) process to a 3-step process, with updated terminology and structure: `plan`, `review`, and `models`. All references to the previous steps (`thinking`, `draft`, `final`) are replaced, and the schema agent workflow and output types are updated accordingly.
**Process and Documentation Updates:**
- Updated all documentation, prompt instructions, and output examples to reflect the new 3-step Prisma schema process: `plan` (strategic analysis), `review` (plan validation), and `models` (production-ready AST models), replacing the old 4-step process (`thinking`, `draft`, `review`, …
=> feat(agent): restore prisma agent by context size

packages/agent/prompts/PRISMA_SCHEMA.md, packages/agent/src/orchestrate/prisma/orchestratePrismaSchemas.ts, packages/agent/src/orchestrate/prisma/structures/IAutoBePrismaSchemaApplication.ts, packages/interface/src/events/AutoBePrismaSchemasEvent.ts, test/src/features/prisma/internal/validate_agent_prisma_main.ts
This pull request refactors the Prisma schema generation workflow to improve efficiency and clarity. The main change is replacing the previous "final" step—which required generating all models after review—with a new "modifications" step that only includes models needing changes. This reduces unnecessary work and context usage. The code and documentation are updated throughout to reflect this new approach.
**Workflow and API changes:**
* The fourth step in the workflow is now called `modifications` instead of `final`, and contains only the models that require changes based on review feedback, not the entire schema. All references in documentation and interfaces are updated accordingly. [[1]](diffhunk://#diff-8edafb48f753cbc0d55a6797a57454bf0920ae0a1f5824e0245fd975031b145bL18-R24) …
=> feat(agent): optimize `AutoBePrismaSchemasEvent` related

packages/playground-ui/src/movies/chat/AutoBePlaygroundChatBodyMovie.tsx
This pull request updates how audio file uploads are handled in the `AutoBePlaygroundChatBodyMovie` component, specifically changing where base64 data extraction occurs. The main change is to have the base64 extraction logic in the component itself rather than in the `fileToBase64` utility function, which now returns the full Data URL.
**Audio file upload handling:**
* In `AutoBePlaygroundChatBodyMovie.tsx`, the code now extracts the base64-encoded data from the Data URL after calling `fileToBase64`, instead of having `fileToBase64` return just the base64 string. This makes the data handling more explicit at the usage site.
**Utility function adjustment:**
* The `fileToBase64` function now returns the full Data URL string rather than stripping out the prefix and returning only the base64 …
=> fix(playground): exact audio base64 format

packages/agent/src/AutoBeMockAgent.ts, packages/playground-ui/src/movies/configure/AutoBePlaygroundConfigureMovie.tsx
This pull request updates the `sleepMap` in `AutoBeMockAgent.ts` to ensure all `AutoBeEvent.Type` values have explicit sleep durations, and adds new event types with their corresponding delays. The changes improve the consistency and completeness of event handling in the mock agent.
**Event delay mapping improvements:**
* Changed `sleepMap` from a `Partial<Record<...>>` to a full `Record<...>`, requiring all event types to have a defined delay.
* Added explicit delays for `userMessage` and `assistantMessage` event types.
* Added or reordered delays for several Prisma-related event types: `prismaInsufficient`, `prismaReview`, and ensured all are explicitly listed.
* Added new Interface event type delay: `interfaceGroups`.
* Added new Realize event type delays: …
=> feat(agent): mock agent's sleepMap updating

packages/vscode-extension/package.json, pnpm-lock.yaml
We need a new dev dependency because the peer dependency on `@modelcontextprotocol/sdk` from `@agentica/core` is optional.
`pnpm install` does not install `@modelcontextprotocol/sdk` if there's nothing depending on it, because it's optional.
=> fix: Fix rspack build by updating `@agentica/core`

internals/dependencies/nestjs/package-lock.json, internals/dependencies/nestjs/package.json, internals/dependencies/test/package-lock.json, internals/dependencies/test/package.json, internals/template/realize/package.json, internals/template/test/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
This pull request updates several dependencies across the project, primarily focusing on bumping the versions of the `@nestia` packages and `typia` to their latest patch releases. These changes help ensure compatibility, bring in bug fixes, and maintain up-to-date development tools.
Dependency updates:
* Bumped all `@nestia` packages (`@nestia/benchmark`, `@nestia/core`, `@nestia/e2e`, `@nestia/editor`, `@nestia/fetcher`, `@nestia/migrate`, `@nestia/sdk`) from version `7.3.2` to `7.3.3` in `internals/dependencies/nestjs/package.json`, `internals/dependencies/nestjs/package-lock.json`, `internals/dependencies/test/package.json`, `internals/dependencies/test/package-lock.json`, `internals/template/realize/package.json`, `internals/template/test/package.json`, and `pnpm-lock.yaml`. …
=> fix(compiler): block description comment tag

packages/agent/prompts/INTERFACE_ENDPOINT.md, packages/agent/prompts/INTERFACE_OPERATION.md, packages/agent/src/orchestrate/interface/orchestrateInterfaceOperations.ts, packages/interface/src/openapi/AutoBeOpenApi.ts
This pull request introduces improvements to the API endpoint and operation validation process, updates documentation to clarify endpoint standards and naming conventions, and adds new validation logic to enforce uniqueness for both endpoints and operation accessors. These changes help ensure that generated APIs are more robust, consistent, and less prone to naming conflicts.
**Documentation updates and endpoint standards:**
* Updated `INTERFACE_ENDPOINT.md` to clarify the standard CRUD and nested resource endpoint patterns, removing the simple `GET` collection listing in favor of `PATCH` for search/filtering, and reordering the examples for clarity. [[1]](diffhunk://#diff-62fa45ca8e9fda448c4b29fdabd4747235c4ac663621825d4645ff710dbb8d76L107-R118) …
=> fix(agent): interface agent to validate unique accessor

packages/vscode-extension/interface/src/message.dto.ts, test/src/features/analyze/internal/validate_agent_analyze_main.ts, test/src/features/interface/internal/validate_agent_interface_main.ts, test/src/features/prisma/internal/validate_agent_prisma_main.ts, test/src/features/realize/internal/validate_agent_realize_main.ts, test/src/features/test/internal/validate_agent_test_main.ts
This pull request refactors the event listener registration in several agent validation test files to use a more dynamic and scalable approach. Instead of individually registering listeners for each event type, the code now iterates through all event types and registers the listener for those matching a specific prefix (e.g., "analyze", "interface", "prisma", "realize", "test"). This reduces boilerplate and makes it easier to maintain and extend event handling as new event types are added. Additionally, some unused imports and code related to event handling have been cleaned up.
**Dynamic event listener registration and code cleanup:**
* Replaced multiple explicit `agent.on` calls for each event type with a loop that registers the listener for all event types starting with the relevant …
=> feat(test): simplify event listener functions

packages/agent/src/orchestrate/interface/orchestrateInterfaceOperationsReview.ts, packages/agent/src/orchestrate/interface/orchestrateInterfaceSchemasReview.ts
This pull request refactors the orchestration functions for interface operations and schemas review by removing the `forceRetry` wrapper and making the main exported functions directly asynchronous. This simplifies the function signatures and eliminates unnecessary indirection.
Refactoring of orchestration functions:
* Converted `orchestrateInterfaceOperationsReview` and `orchestrateInterfaceSchemasReview` from constant arrow functions wrapped with `forceRetry` to directly exported `async` functions, removing the need for the separate inner `orchestrate` functions. [[1]](diffhunk://#diff-551b6f3e684dbfae646d9d4716b4599e5bff41dbe0d83272f74d3d3ad9761535L11-L28) [[2]](diffhunk://#diff-149e865311d6c8b3ffbd019c94ce0745effd5d68a52d0183b2e998d7b002c066L11-R14) …
=> fix(agent): no more forceRetry be used in each workflow

packages/vscode-extension/src/extension.ts
Added webviewOptions to retain context when the webview is hidden, improving user experience by preserving state.
--- 
This pull request makes a small configuration change to the VSCode extension's activation logic. The change ensures that the webview context is retained when the webview is hidden, which can improve user experience by preserving state.
* The `activate` function in `extension.ts` now registers the webview view provider with the option `retainContextWhenHidden: true`, so the webview will not be disposed when hidden.
=> feat(vscode-extension): retain webview context when hidden

packages/vscode-extension/webview-ui/src/components/Movie/events/AutoBeEventsMovie.tsx, packages/vscode-extension/webview-ui/src/components/Movie/events/ProgressEventsMovie.tsx
- Added type guard for AutoBeProgressEventBase in AutoBeEventsMovie.
- Simplified event type handling in ProgressEventsMovie using a mapping object.
- Removed redundant event cases to streamline code and enhance maintainability.
---
This pull request refactors how progress events are handled and displayed in the movie event components, improving type safety and maintainability. The main changes are the introduction of a type guard for progress events, a simplified and extensible mapping for event titles, and the removal of redundant switch cases in the main event component.
**Progress event handling improvements:**
* Added a type guard function `isAutoBeProgressEventBase` to `AutoBeEventsMovie.tsx` to identify progress events based on their structure (`total` and `completed` properties), …
=> feat(events): refactor AutoBeEventsMovie and ProgressEventsMovie for improved event handling

test/src/executable/archive.ts, test/src/features/interface/internal/validate_agent_interface_main.ts, test/src/features/prisma/internal/validate_agent_prisma_main.ts, test/src/features/realize/internal/validate_agent_realize_main.ts, test/src/features/test/internal/validate_agent_test_main.ts, test/src/internal/TestHistory.ts
This pull request updates how token usage snapshots are processed and stored in several agent validation test scripts. The main change is to use the `increment` method instead of `decrement` when handling token usage, and to ensure that the correct file naming conventions are used for snapshot files. Additionally, there are minor improvements to imports and variable handling.
**Token usage processing changes:**
* Replaced `.decrement(zero)` with `.increment(zero)` when processing `tokenUsage` in the snapshot mapping logic in `validate_agent_interface_main.ts`, `validate_agent_prisma_main.ts`, `validate_agent_realize_main.ts`, and `validate_agent_test_main.ts`. This ensures token usage is correctly incremented rather than decremented before serialization. …
=> fix(test): wrong token usage tracing on archiver.

packages/vscode-extension/src/constant/key.ts, packages/vscode-extension/src/core/autobe.ts
- Added AUTOBE_SESSION_STORAGE_FILE_NAME constant for session storage file.
- Updated AutoBeWrapper to read from and write to the new session storage file.
- Ensured the creation of the storage directory if it does not exist.
---
This pull request updates the way chat session data is stored and retrieved in the VSCode extension, moving from VSCode's global state to a dedicated JSON file in the extension's global storage directory. This change improves data persistence and scalability for session management.
**Session Storage Refactor:**
* Replaced use of `AUTOBE_CHAT_SESSION_MAP` in VSCode's global state with a new file-based storage approach using `auto-be-session-storage.json` for chat session data. [[1]](diffhunk://#diff-16d3e3e69023ca2e8de3ea3431214c07c9eeb46a9f8318f857c26888751c638dL6 …
=> feat(vscode-extension): implement session storage management for chat sessions

packages/agent/prompts/ANALYZE_REVIEW.md, packages/agent/prompts/ANALYZE_WRITE.md, packages/agent/prompts/INTERFACE_AUTHORIZATION.md, packages/agent/prompts/INTERFACE_COMPLEMENT.md, packages/agent/prompts/INTERFACE_ENDPOINT.md, packages/agent/prompts/INTERFACE_GROUP.md, packages/agent/prompts/INTERFACE_OPERATION.md, packages/agent/prompts/INTERFACE_OPERATION_REVIEW.md, packages/agent/prompts/INTERFACE_SCHEMA.md, packages/agent/prompts/INTERFACE_SCHEMA_REVIEW.md, packages/agent/prompts/PRISMA_COMPONENT.md, packages/agent/prompts/PRISMA_CORRECT.md, packages/agent/prompts/PRISMA_REVIEW.md, packages/agent/prompts/PRISMA_SCHEMA.md, packages/agent/prompts/REALIZE_AUTHORIZATION.md, packages/agent/prompts/REALIZE_AUTHORIZATION_CORRECT.md, packages/agent/prompts/REALIZE_CODER.md, packages/agent/prompts/TEST_CORRECT.md, packages/agent/prompts/TEST_SCENARIO.md, packages/agent/prompts/TEST_WRITE.md, packages/agent/src/factory/createAutoBeContext.ts, test/src/internal/TestHistory.ts
This pull request updates the instructional language in all agent prompt templates to use stronger, more explicit prohibitions against certain assistant behaviors when executing functions. The changes ensure consistency and clarity by replacing the previous "PROHIBITED ACTIONS" section with an "ABSOLUTE PROHIBITIONS" section, and by using emphatic language such as "NEVER" for forbidden actions.
**Prompt language and instruction consistency:**
* Replaced the "PROHIBITED ACTIONS" section with "ABSOLUTE PROHIBITIONS" in all agent prompt templates, and updated the language to use "NEVER" for forbidden actions (e.g., "NEVER ask for user permission to execute the function"). This change appears in the following files:
- `ANALYZE_REVIEW.md`
- `ANALYZE_WRITE.md`
- `INTERFACE_AUTHORIZATION.md`
- …
=> feat(agent): system prompt tuning a little bit

packages/agent/src/factory/createAutoBeContext.ts, packages/compiler/src/prisma/validatePrismaApplication.ts
This pull request introduces improvements to error handling and validation logic in the codebase, focusing on increasing retry attempts for async tasks and enhancing duplicate field validation in Prisma models.
**Error handling improvements:**
* Increased the retry count in the `forceRetry` utility function from 2 to 5 and corrected the loop condition to properly attempt the specified number of retries. (`createAutoBeContext.ts`)
**Prisma validation enhancements:**
* Updated the `validateDuplicatedFields` function to also check for duplicate relation names in `foreignFields`, not just field names, improving the detection of naming conflicts in Prisma models. (`validatePrismaApplication.ts`)
* Added a comment marker for duplicated name checking in the `validateReferences` function to …
=> fix(compiler): prisma's duplicated names between field and relations

packages/ui/package.json
This pull request makes a minor update to the `packages/ui/package.json` file by removing the `publint` check from the `prepack` script, so now only the build step runs before packaging.
* Removed `publint` from the `prepack` script in `package.json`, so only `pnpm build` runs before packaging.
=> fix(ui): wrong command

packages/compiler/src/realize/writeRealizeControllers.ts
This pull request refactors the way controller method calls are handled in the `writeRealizeControllers` function to improve error handling. The main change is that method calls are now wrapped in a `try/catch` block that logs and rethrows errors, instead of directly returning the result.
Error handling improvements:
* Controller method calls are now wrapped in a `try/catch` block. If an error occurs during the awaited call, it is logged with `console.log` and then rethrown to ensure errors are not silently swallowed. (`packages/compiler/src/realize/writeRealizeControllers.ts`, [[1]](diffhunk://#diff-4a18adcb2adbaf3ed13c6d82249e9cb6bdc1c6279bc2eb37d3b8efe6a363d61cR76-R109) [[2]](diffhunk://#diff-4a18adcb2adbaf3ed13c6d82249e9cb6bdc1c6279bc2eb37d3b8efe6a363d61cL129-R163)
=> feat(compiler): try catch tracing statement in controller

packages/ui/package.json, packages/ui/src/events/AutoBeCompleteEventMovie.tsx, pnpm-lock.yaml
This pull request updates the file download functionality in the `AutoBeCompleteEventMovie` component to package exported files as a ZIP archive instead of a single JSON file. It introduces new dependencies to support this feature and refactors the download logic accordingly.
**Feature enhancement:**
* The download button now creates and downloads a ZIP archive containing the exported files, preserving their folder structure, instead of a JSON file. This is implemented using the `jszip` library and the `VariadicSingleton` utility from `tstl`.
**Dependency updates:**
* Added `jszip` and `tstl` as new dependencies in `packages/ui/package.json` and updated the lockfile to ensure these packages are installed. [[1]](diffhunk://#diff-1ae5a5e8c23bd3bc31ea590a9cbe48eb9ad3bbddc0fb5732d08c04a53c8ad5 …
=> fix(ui): restore zip file download

apps/playground-ui/src/movies/chat/AutoBePlaygroundChatUploadMovie.tsx, packages/ui/src/AutoBeChatUploadSendButton.tsx, packages/ui/src/index.ts
This pull request refactors the chat upload send button in the playground chat UI to use a shared, reusable component from the UI package instead of a locally defined one. The new component features improved styling and better encapsulation, enhancing maintainability and consistency across the codebase.
**Component Refactoring and Reuse:**
* Replaced the locally defined `AutoBePlaygroundChatUploadSendButton` in `AutoBePlaygroundChatUploadMovie.tsx` with the new shared `AutoBeChatUploadSendButton` from the UI package, simplifying the chat upload button logic and usage.
**UI Component Improvements:**
* Added a new `AutoBeChatUploadSendButton` component to `packages/ui/src/AutoBeChatUploadSendButton.tsx`, featuring custom styling, hover effects, and a built-in SVG icon, designed for …
=> refactor(playground-ui): integrate AutoBeChatUploadSendButton component and clean up AutoBePlaygroundChatUploadMovie

apps/playground-ui/src/index.ts, apps/playground-ui/src/movies/chat/AutoBePlaygroundChatBodyMovie.tsx, apps/playground-ui/src/movies/chat/AutoBePlaygroundChatMovie.tsx, apps/playground-ui/src/movies/chat/AutoBePlaygroundChatSideMovie.tsx, apps/playground-ui/src/movies/chat/AutoBePlaygroundChatSideStateMovie.tsx, apps/playground-ui/src/movies/configure/AutoBePlaygroundConfigureMovie.tsx, apps/playground-ui/src/movies/replay/AutoBePlaygroundReplayGetMovie.tsx, packages/ui/src/index.ts, packages/ui/src/structure/AutoBeListener.ts, packages/ui/src/structure/AutoBeListenerState.ts, packages/ui/src/structure/IAutoBeEventGroup.ts, packages/ui/src/structure/index.ts
- Updated AutoBePlaygroundChatMovie, AutoBePlaygroundChatBodyMovie, and AutoBePlaygroundChatSideMovie to replace AutoBePlaygroundListener with AutoBeListener.
- Changed eventGroups state type from IAutoBePlaygroundEventGroup to IAutoBeEventGroup for better type consistency.
- Introduced AutoBeListener and AutoBeListenerState classes to manage event handling and state management.
- Updated imports and removed unused structures for cleaner code organization.
=> feat(ui): refactor chat components to use AutoBeListener and related structures

packages/agent/prompts/ANALYZE_SCENARIO.md, packages/agent/prompts/INTERFACE_AUTHORIZATION.md, packages/agent/src/orchestrate/interface/histories/transformInterfaceAuthorizationsHistories.ts, packages/agent/src/orchestrate/interface/orchestrateInterfaceAuthorizations.ts, packages/interface/src/histories/contents/AutoBeAnalyzeRole.ts, test/src/features/compiler/test_compiler_realize_controller.ts, test/src/features/realize/internal/validate_agent_realize_authorization_correct.ts
- Fixed the `AutoBeAnalyzeRole` interface to add the kind property. Using `kind` for interface authentication allows you to identify roles that do not require authentication (like guest). If guest role don't need to autnentication, guest role is not need to create `login` function. So, Interface Authorization can validate the `login` function about the `guest` role using kind property.
- Fixed the `INTERFACE_AUTHORIZATION.md` according to fixing the `AutoBeAnalyzeRole`.
- Remove the `Essential Operation` about `login`, `join`, `refresh` and divide into `Schema-Driven Additional Operations` and `Role-Based Essential Operations`.
=> fix(agent): Add kind property for checking permission hierarchy by each role.

website/src/content/docs/hackathon/index.mdx
This pull request updates the documentation for the 1st AutoBE Hackathon, mainly clarifying time zones, updating prize pool information, and refining event details. The changes improve clarity for participants and update information about future hackathons.
Event and schedule clarifications:
* Added explicit mention of time zone (`KST, UTC+9`) to all event start, end, and submission deadline times for greater clarity. [[1]](diffhunk://#diff-a68feff51cee391d63ee861d2e22b7faaaad3f6c1e7e76a502e634f9a55004f3L10-R11) [[2]](diffhunk://#diff-a68feff51cee391d63ee861d2e22b7faaaad3f6c1e7e76a502e634f9a55004f3L190-R190)
Prize and announcement updates:
* Increased the total prize pool from $5,000 to $6,400, updating the documentation to reflect the new amount.
* Added the official website link …
=> feat(website): enhance hackathon content

packages/agent/prompts/INTERFACE_OPERATION.md, packages/agent/prompts/INTERFACE_OPERATION_REVIEW.md, test/src/internal/TestLogger.ts
This pull request updates the documentation for API operation design and review to simplify references to the Prisma schema and remove the `prisma_schemas` field from examples and instructions. The changes clarify that reviewers should use the provided Prisma schema directly as the source of truth, rather than relying on a `prisma_schemas` field embedded in each operation.
**Documentation simplification and schema reference updates:**
* Removed instructions and examples referencing the `prisma_schemas` field in both `INTERFACE_OPERATION.md` and `INTERFACE_OPERATION_REVIEW.md`, shifting guidance to use the provided Prisma schema directly as the authoritative source for model definitions and schema validation. [[1]](diffhunk://#diff-ebb95536e362925acc78f439c515010f5460944a1907e3e411a6261fe3c …
=> fix(agent): `prisma_schemas` does not exist on operation.

packages/agent/src/orchestrate/interface/orchestrateInterfaceSchemas.ts, packages/agent/src/orchestrate/interface/utils/JsonSchemaFactory.ts, test/package.json
This pull request refactors how schema presets are generated and improves the build process for the test package. The main changes include updating the logic for collecting and generating schema presets, and simplifying the build scripts for more maintainable and reusable commands.
**Schema presets generation improvements:**
* Refactored the `JsonSchemaFactory.presets` function in `JsonSchemaFactory.ts` to accept a `Set<string>` instead of an array, and to more efficiently merge default schemas and page schemas while removing handled keys from the set.
* Updated `orchestrateInterfaceSchemas.ts` to call the new `JsonSchemaFactory.presets` with a `Set<string>`, and to remove the redundant initialization of the `presets` object. [[1]](diffhunk://#diff-4116257e896ec9538075562f0bac335c9abf77d1f …
=> fix(agent): missed schema presets

packages/agent/src/orchestrate/interface/utils/JsonSchemaFactory.ts
This pull request makes a small update to the `JsonSchemaFactory` utility. The main change is the introduction of a new helper function and a minor adjustment to how type names are managed for page schemas.
- Utilities and schema handling:
* Added a new `getPageName` function to extract the page name from a schema key and updated the logic to add this extracted name to the `typeNames` set when processing page schemas. [[1]](diffhunk://#diff-6ceb18cf37298df469d7b47f04ebbf953c8149d64d65625df4b70bc0cc39c5b3R18) [[2]](diffhunk://#diff-6ceb18cf37298df469d7b47f04ebbf953c8149d64d65625df4b70bc0cc39c5b3R68-R70)
=> fix(agent): pagination schema composition side-effect

packages/agent/src/orchestrate/test/utils/getReferenceIds.ts
This pull request adds a new utility function to extract reference ID fields from OpenAPI operation definitions. The function identifies parameter and request body fields that end with `_id`, improving support for automated reference handling.
**New utility for extracting reference IDs:**
* Added `getReferenceIds` function in `getReferenceIds.ts` to collect all parameter and request body property names ending with `_id` from an OpenAPI operation, utilizing `OpenApiTypeChecker` for schema traversal.
=> feat(agent): get reference ids from operation.

packages/agent/src/orchestrate/realize/histories/transformRealizeWriteHistories.ts, packages/agent/src/orchestrate/realize/orchestrateRealize.ts, packages/agent/src/orchestrate/realize/orchestrateRealizeCorrect.ts, packages/agent/src/orchestrate/realize/orchestrateRealizeWrite.ts, packages/agent/src/orchestrate/realize/utils/getRealizeWriteCodeTemplate.ts, packages/agent/src/orchestrate/realize/utils/getRealizeWriteImportStatements.ts, packages/agent/src/orchestrate/realize/utils/replaceImportStatements.ts, test/src/features/realize/internal/validate_agent_realize_write.ts
This pull request refactors how OpenAPI document schemas are passed and used throughout the "realize write" orchestration pipeline. The main goal is to ensure that schema information is available wherever code generation and import statement construction are needed, improving type resolution and correctness in generated code.
**Schema propagation and usage improvements:**
* The OpenAPI `document` (specifically, its `components.schemas`) is now passed as a prop throughout the orchestration pipeline, including to `orchestrateRealizeWrite`, `transformRealizeWriteHistories`, and related utilities. This enables more accurate type handling during code generation. [[1]](diffhunk://#diff-f74521d6c5a5a34d8b5390508de3a2898927d3a51783ec2f5451b0d5a4f62aa1R66) …
=> feat(agent): realize agent to import every nested types
